### ISSUE TITLE
approve pending subscription fails

### ISSUE THREAD

**Issue by liedekef** [sympa-community/sympa#1443] opened 2022-07-14 12:03 UTC
Version
-------
6.2.66~dfsg-2

Installation method
-------------------
basic install via dpkg and official ubuntu repo on ubuntu 22

Expected behavior
-----------------
a pending subscriber should be able to be accepted. 

Actual behavior
---------------
In this case my test user frankty@e-dynamics.be was visible in the list of pending subscriptions, but when approving it, it just disappeared. I received the popup that it was added to the list, but it was not. I received a list "internal error" mail on the list owner address.

Steps to reproduce
------------------
send a mail to xxx-subscribe@mylist with an email with a dash in the domain name

Additional information
----------------------
Jul 14 11:24:27 lists wwsympa[431236]: err main::#1554 > main::do_auth_add#7177 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::auth::_twist#65 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::add::_twist#115 > Sympa::List::add_list_member#3280 > Sympa::DatabaseDriver::PostgreSQL::do_prepared_query#112 > Sympa::Database::do_prepared_query#389 Unable to execute SQL statement "INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_epoch_subscriber, update_epoch_subscriber, inclusion_subscriber, inclusion_ext_subscriber, inclusion_label_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)": (25P02) ERROR:  current transaction is aborted, commands ignored until end of transaction block
Jul 14 11:24:27 lists wwsympa[431236]: err main::#1554 > main::do_auth_add#7177 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::auth::_twist#65 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::add::_twist#115 > Sympa::List::add_list_member#3315 Unable to add subscriber franky@e-dynamics.be to table subscriber_table for list xxx@mylist
Jul 14 11:24:27 lists wwsympa[431236]: err main::#1554 > main::do_auth_add#7177 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::auth::_twist#65 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::add::_twist#115 > Sympa::List::add_list_member#3315 Unable to add subscriber franky@e-dynamics.be to table subscriber_table for list xxx@mylist

No real useful logs though, so I'm guessing a bug in the domain parsing part. Since almost any character is now allowed, I'd suggest a regex like the one I use in php now:

/^[\w\-\.\+]+@([\w\-]+\.)+[\w\-]{2,63}$/u

Can I add/test anything else?

**Comment by ikedas** [comment] 2022-07-15 08:23
> ``` code
> (25P02) ERROR: current transaction is aborted, commands ignored until end of transaction block
> ```

This is a bug during 6.2.66 to 6.2.68, due to the same cause of #1359.  It will be fixed on the next release (maybe 6.2.70).

For quick fix, please apply [this patch](https://github.com/sympa-community/sympa/commit/5df70d8.patch) and check if the problem is solved.

**Closed** 2022-12-25 00:56 UTC
Labels: bug
