### ISSUE TITLE
Avoid "subscribe spam"

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#302] opened 2018-05-15 12:31 UTC
- if the subscriber is already is the subscription to moderate list, Sympa should not send a new mail to moderators
- if the subscriber is in the blacklist, no mail shoud be sent either.

We had the case where someone in the blacklist send subscription mails again and again, and the moderator got mail notification again and again.

Seen on 6.2.16

**Comment by ikedas** [comment] 2018-05-16 05:45
Hi @ldidry,

Can you show us configuration of your Sympa, especially things below?
- `subscribe` parameter in list `config`
- `use_blacklist` parameter in `sympa.conf` or (if any) `robot.conf`

**Comment by ldidry** [comment] 2018-05-16 08:17
The list config:
```
config.0:subscribe owner
```

`sympa.conf`:
```
use_blacklist   send,create_list
```

Ok, I see now that `sympa.conf` should use `subscribe` as well, is it that?

What are the valid values for `use_blacklist`? I'll add them to the documentation.

**Comment by ikedas** [comment] 2018-05-16 09:12
> Ok, I see now that `sympa.conf` should use `subscribe` as well, is it that?
> What are the valid values for `use_blacklist`? I'll add them to the documentation.

Yes, in the second case you reported, you may have to add `subscribe` to the value of `use_blacklist` parameter.  If the problem disappeared by this change, the second case is not a bug.

I'll investigate the first case further.

**Comment by ikedas** [comment] 2018-05-28 04:39
Hi @ldidry,
About the firset case:
> - if the subscriber is already is the subscription to moderate list, Sympa should not send a new mail to moderators

Please show us:
- Configuration of the list in question.
- Procedure to reproduce problem.

Thanks.

**Comment by ikedas** [comment] 2018-08-12 06:58
Hi @ldidry,

With PR #390, I think the first case will never occur, because, for example in [`subscribe.auth`](https://github.com/sympa-community/sympa/blob/a51f2c8/default/scenari/subscribe.auth) scenario:
``` code
# subscribe.auth
title.gettext subscription request confirmed

!equal([sender],[email])           smtp,dkim,md5,smime -> request_auth([email])
is_subscriber([listname],[email])  smtp,dkim,md5,smime -> do_it
true()                             smtp,dkim           -> request_auth([email])
true()                             md5,smime           -> do_it
```
If the user has already subscribed, `do_it` is returned, and `subscribe` request will fail with a response "The User '...' is already subscriber of list '...'."

**Comment by ldidry** [comment] 2018-08-12 08:13
> Please show us:

>    Configuration of the list in question.
>    Procedure to reproduce problem.

Sorry, I didn't see the message. And now, I don't remember which list it was.

Glad to see that #390 will solve the case.

I'll test the case once I updated our Sympa and applied the patch (in two days)

**Comment by ikedas** [comment] 2018-09-04 05:41
Solved. Thanks for reporting bug! Closing.

**Closed by ikedas** 2018-09-04 05:41 UTC
Labels: bug
