### ISSUE TITLE
mhonarc-ressources.tt2 uses inconsistent date formats

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#689] opened 2019-07-12 10:57 UTC
Expected Behavior
-----------------

I would like archived.pl / mhoarc to use  European date formats (%d/%m/%Y).

Alternatively ISO 8601 date formats (%Y-%m-%d)  which have the advantage of being unambiguous.

Current Behavior
----------------

Sympa mostly uses American middle endian date formats (%m/%d/%Y).

However the "Chronological" tab uses %y/%m/%d to start each new day.

Possible Solution
-----------------

My existing workaround is a custom mhonarc-ressources.tt2  file.

Would it be possible to add a configuration option which is referenced in the default file instead?

Context
-------

My users do not normally use American middle endian date formats.

07/01/2019 would normally be read as 7th January 2019 rather than 1st July 2019.

**Comment by ikedas** [comment] 2019-07-12 12:52
Hi @dpc22,
> Sympa mostly uses American middle endian date formats (%m/%d/%Y).

Where is it used? Could you show screen shot?

**Comment by dpc22** [comment] 2019-07-12 13:02
https://listes.renater.fr/sympa/arc/sympa-developpers/2019-07/ includes:

```
Re: [sympa-developpers] Sympa web site updated IKEDA Soji, 07/05/2019
```
That message was sent on 5th July 2019. In addition:

https://listes.renater.fr/sympa/arc/sympa-developpers/2019-07/mail1.html contains:

```
19/07/05
...
19/07/06
...
19/07/07
```
which are year/month/date

**Comment by ikedas** [comment] 2019-07-16 07:36
Duplicate of #115.

You may correct English translation [here](https://translate.sympa.org/en_US/sympa/translate/en_US.po#unit=61082) (sign-in is needed to correct it).

**Closed by ikedas** 2019-07-16 07:36 UTC

**Comment by dpc22** [comment] 2019-07-17 08:49
(Sorry if this reopens the ticket: it seemed sensible to attach the following text to the original ticket),

The existing translation is fine for en_US.

It looks like I would need a dedicated en_GB locale for the differences between American and British English. Maintaining my own mhonarc-ressources.tt2 might be the fastest/simplest workaround given that this is the only issue that I have run into to date.

However thanks for pointing out that the localisation stuff can also transform date strings. That hadn't occurred to me.

**Comment by bboyle262** [comment] 2025-05-22 21:45
65y6r
