### ISSUE TITLE
unable to send mail to list address (error  Recipient address rejected: User unknown in local recipient table)

### ISSUE THREAD

**Issue by bv-unibs** [sympa-community/sympa#715] opened 2019-08-01 07:45 UTC
Hi,
I'm using sympa version 6.2.40 from debian 10 repo with postfix version 3.4.5.
I followed through the guide for configuring postfix with sympa:
https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html
I chose the simplest configuration (single domain setting) that's is suitable for my situation..

I think I followed all the steps reported in the documentation but trying send email to postfix I always obtain the error "recipient address rejected: user unknown in local recipient table), like postfix is unable to read the sympa aliases file.

Then i tried to add to main.cf in postfix conf the parameter:
local_recipient_maps = $alias_maps, which is missing in the documentation, but still I can't send the email to my lists.

Can you help me troubleshoot this issue?

thanks

**Comment by racke** [comment] 2019-08-01 07:56
Can you post your main.cf, especially the relay and the alias settings?

**Comment by bv-unibs** [comment] 2019-08-01 08:09
> smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_client_restrictions = permit_mynetworks
myhostname = smtpout.unibs.it
mydomain = unibs.it
alias_maps = hash:/etc/aliases,hash:/etc/postfix/aliases.sympa.postfix
alias_database = hash:/etc/aliases,hash:/etc/postfix/aliases.sympa.postfix
myorigin = $mydomain
mydestination = $myhostname, localhost.$mydomain, liste.$mydomain
local_recipient_maps = $alias_maps
#relayhost = 
mailbox_size_limit = 0
message_size_limit = 26214400
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

> 

this is the relevant section of main.cf

**Comment by racke** [comment] 2019-08-01 08:27
I don't have a straight answer, maybe you could try to put the Sympa domain into relay_domains. At any rate you can postfix tell to log with a lot of verbosity to see how it processes the emails: http://www.postfix.org/DEBUG_README.html#verbose

**Comment by bv-unibs** [comment] 2019-08-01 08:51
I put the postfix log in debug mode from the peer i use to send my email and this is the result in the log:

maps_find: recipient_canonical_maps: dba@liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: **maps_find: recipient_canonical_maps: dba: not found**
Aug  1 10:40:08 liste postfix/smtpd[1923]: **maps_find: recipient_canonical_maps: @liste.unibs.it: not found**
Aug  1 10:40:08 liste postfix/smtpd[1923]: mail_addr_find: dba@liste.unibs.it -> (not found)
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: canonical_maps: dba@liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: canonical_maps: dba: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: canonical_maps: @liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: mail_addr_find: dba@liste.unibs.it -> (not found)
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: virtual_alias_maps: dba@liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: virtual_alias_maps: dba: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: virtual_alias_maps: @liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: mail_addr_find: dba@liste.unibs.it -> (not found)
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: local_recipient_maps: dba@liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: local_recipient_maps: dba: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: maps_find: local_recipient_maps: @liste.unibs.it: not found
Aug  1 10:40:08 liste postfix/smtpd[1923]: mail_addr_find: dba@liste.unibs.it -> (not found)

**Comment by racke** [comment] 2019-08-01 08:59
Looks like dba@liste.unibs.it is not known as recipient? Where did you put the alias for this address?

**Comment by bv-unibs** [comment] 2019-08-01 09:08
This is one the sympa mailing lists I have on my server. I supposed with the postfix sympa configuration above, sympa creates the aliases needed for all the mailing lists to be used by postfix..

**Comment by bv-unibs** [comment] 2019-08-01 09:10
I don't know If I'm forgetting something..

**Comment by racke** [comment] 2019-08-01 09:12
Double check your aliases for this address please. Did you add the alias entries to sympa.conf as described in instruction 1. ?

**Comment by bv-unibs** [comment] 2019-08-01 09:17
Yes I did:
in the sympa.conf file i put this:

> domain  liste.unibs.it
aliases_program postalias
sendmail /usr/sbin/sendmail
> 

then i created the file  aliases.sympa.postfix with this content, as mentioned in documentation:

> 
# Robot aliases for Sympa.
sympa:                 "| /usr/lib/sympa/bin/queue sympa@liste.unibs.it"
listmaster:            "| /usr/lib/sympa/bin/queue listmaster@liste.unibs.it"
bounce:                "| /usr/lib/sympa/bin/bouncequeue sympa@liste.unibs.it"
abuse-feedback-report: "| /usr/lib/sympa/bin/bouncequeue sympa@liste.unibs.it"
sympa-request:         postmaster
sympa-owner:           postmaster
> 

Then I used the command postalias on the sympa.alias.postfix file

**Comment by racke** [comment] 2019-08-01 09:27
Did you try to send email to one of the aliases above, e.g. sympa@liste.unibs.it or listmaster@liste.unibs.it?

**Comment by racke** [comment] 2019-08-01 09:29
I suppose the problem is that /etc/aliases doesn't contain the list aliases for dba list (no permissions?). I would recommend to use a separate alias file for Sympa lists as described in the virtual domain settings.

**Comment by bv-unibs** [comment] 2019-08-01 09:30
I tried with listmaster and seems the alias is working for this one:

Aug  1 11:28:29 liste postfix/smtpd[2157]: maps_find: canonical_maps: listmaster@liste.unibs.it: not found
Aug  1 11:28:29 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 11:28:29 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 11:28:29 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 11:28:29 liste postfix/smtpd[2157]: maps_find: canonical_maps: listmaster: not found
Aug  1 11:28:29 liste postfix/smtpd[2157]: maps_find: canonical_maps: @liste.unibs.it: not found
Aug  1 11:28:29 liste postfix/smtpd[2157]: mail_addr_find: listmaster@liste.unibs.it -> (not found)
Aug  1 11:28:29 liste postfix/smtpd[2157]: maps_find: virtual_alias_maps: listmaster@liste.unibs.it: not found
Aug  1 11:28:29 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 11:28:29 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 11:28:30 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 11:28:30 liste postfix/smtpd[2157]: maps_find: virtual_alias_maps: listmaster: not found
Aug  1 11:28:30 liste postfix/smtpd[2157]: maps_find: virtual_alias_maps: @liste.unibs.it: not found
Aug  1 11:28:30 liste postfix/smtpd[2157]: mail_addr_find: listmaster@liste.unibs.it -> (not found)
Aug  1 11:28:30 liste postfix/smtpd[2157]: maps_find: local_recipient_maps: listmaster@liste.unibs.it: not found
Aug  1 11:28:30 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 11:28:30 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 11:28:30 liste postfix/smtpd[2157]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 11:28:30 liste postfix/smtpd[2157]: maps_find: local_recipient_maps: hash:/etc/postfix/aliases.sympa.postfix(0,lock|fold_fix|utf8_request): listmaster = "| /usr/lib/sympa/bin/queue listmaster@liste.unibs.it"
Aug  1 11:28:30 liste postfix/smtpd[2157]: mail_addr_find: listmaster@liste.unibs.it -> "| /usr/lib/sympa/bin/queue listmaster@liste.unibs.it"
Aug  1 11:28:30 liste postfix/smtpd[2157]: before input_transp_cleanup: cleanup flags = enable_header_body_filter enable_automatic_bcc enable_address_mapping enable_milters
Aug  1 11:28:30 liste postfix/smtpd[2157]: after input_transp_cleanup: cleanup flags = enable_header_body_filter enable_automatic_bcc enable_address_mapping
Aug  1 11:28:30 liste postfix/smtpd[2157]: name_mask: sendmail
Aug  1 11:28:30 liste postfix/smtpd[2157]: name_mask: verify
Aug  1 11:28:30 liste postfix/smtpd[2157]: connect to subsystem public/cleanup
Aug  1 11:28:30 liste postfix/smtpd[2157]: public/cleanup socket: wanted attribute: queue_id
Aug  1 11:28:30 liste postfix/smtpd[2157]: input attribute name: queue_id
Aug  1 11:28:30 liste postfix/smtpd[2157]: input attribute value: 01EBF60C40
Aug  1 11:28:30 liste postfix/smtpd[2157]: public/cleanup socket: wanted attribute: (list terminator)
Aug  1 11:28:30 liste postfix/smtpd[2157]: input attribute name: (end)
Aug  1 11:28:30 liste postfix/smtpd[2157]: send attr flags = 178
Aug  1 11:28:30 liste postfix/smtpd[2157]: 01EBF60C40: client=unknown[10.0.0.1]
Aug  1 11:28:30 liste postfix/smtpd[2157]: > unknown[10.0.0.1]: 250 2.1.5 Ok

**Comment by bv-unibs** [comment] 2019-08-01 09:32
I confirm that /etc/aliases doesn't contain any mailing alias... 

How can I do to popolate with the sympa mailing list alias?

These mailing lists where imported from a previous installation, I have to do some further operation for update the aliases? 

thanks

**Comment by racke** [comment] 2019-08-01 09:35
I suppose you can copy the aliases from the previous installation.

**Comment by bv-unibs** [comment] 2019-08-01 09:40
Yes, I think it can works for the previous lists, but I tried to create a new mailing list from scratch using the web interface: test-new-sympa@liste.unibs.it.

I would expect the alias for this list to be created automatically after the list creation, but I receive the same error when i try to send an email to this mailing list just created:

Aug  1 11:38:08 liste postfix/smtpd[2188]: maps_find: local_recipient_maps: test-new-sympa@liste.unibs.it: not found
Aug  1 11:38:08 liste postfix/smtpd[2188]: match_string: mydestination: liste.unibs.it ~? smtpout.unibs.it
Aug  1 11:38:08 liste postfix/smtpd[2188]: match_string: mydestination: liste.unibs.it ~? localhost.unibs.it
Aug  1 11:38:08 liste postfix/smtpd[2188]: match_string: mydestination: liste.unibs.it ~? liste.unibs.it
Aug  1 11:38:08 liste postfix/smtpd[2188]: maps_find: local_recipient_maps: test-new-sympa: not found
Aug  1 11:38:08 liste postfix/smtpd[2188]: maps_find: local_recipient_maps: @liste.unibs.it: not found
Aug  1 11:38:08 liste postfix/smtpd[2188]: mail_addr_find: test-new-sympa@liste.unibs.it -> (not found)
Aug  1 11:38:08 liste postfix/smtpd[2188]: NOQUEUE: reject: RCPT from unknown[10.0.0.1]: 550 5.1.1 <test-new-sympa@liste.unibs.it>: Recipient address rejected: User unknown in local recipient table; from=<battista.vaccaro@unibs.it> to=<test-new-sympa@liste.unibs.it> proto=SMTP
Aug  1 11:38:08 liste postfix/smtpd[2188]: > unknown[10.0.0.1]: 550 5.1.1 <test-new-sympa@liste.unibs.it>: Recipient address rejected: User unknown in local recipien

**Comment by racke** [comment] 2019-08-01 09:43
Check Sympa logs. It might not have the permissions to write to the alias file.

**Comment by bv-unibs** [comment] 2019-08-01 09:45
I checked sympa.log but I don't see any error, but something is missing..

**Comment by racke** [comment] 2019-08-01 10:02
Permissions of /etc/aliases?

**Comment by bv-unibs** [comment] 2019-08-01 10:49
rw-r----- 1 root root 210 lug 31 12:08 /etc/aliases

**Comment by racke** [comment] 2019-08-01 10:54
So Sympa can't add aliases to this file.

**Comment by bv-unibs** [comment] 2019-08-01 11:36
I managed to solve the problem for the old lists, I copied their aliases in a separate file, and It seems working..

I  changed the permissions of /etc/aliases file for permit sympa user to write the file, but creating a new list I still don't see the alias created..

**Comment by bv-unibs** [comment] 2019-08-01 11:36
So the problem is now regarding the new lists create from now onward..
seems like automated alias creation is not working

**Comment by bv-unibs** [comment] 2019-08-02 07:13
Hi, for workaround the problem about the permissions I added a new alias file under the ownership of sympa user in main.cf of postfix:

/var/lib/sympa/sympa_aliases

In this file I included all my previous lists and these seems to be working, but now the problem is this file doesn't seem to be used by sympa alias manager after creating a new list.
Can you tell me how can I troubleshoot this specific issue? There's a way I can understand where the alias manager of sympa is failing during the alias creation after a new list is created on web interface?

thanks

**Comment by bv-unibs** [comment] 2019-08-02 09:35
I noticed in my virtualhost apache log for sympa the following error during the creation of a new list, I don't know if it's related with the current issue:

mod_fcgid: stderr: [Fri Aug  2 11:32:13 2019] wwsympa.fcgi: Use of uninitialized value in string ne at /usr/share/sympa/lib/Sympa/Spindle/AuthorizeRequest.pm line 118.,

**Comment by racke** [comment] 2019-08-05 08:55
Closing in favour of the more specific issue #718

**Closed by racke** 2019-08-05 08:55 UTC
Labels: question
