### ISSUE TITLE
DMARC rewrites switched

### ISSUE THREAD

**Issue by tmclaren** [sympa-community/sympa#1678] opened 2023-06-07 15:19 UTC
DKIM/DMARC/ARC - DMARC Protection (dmarc_protection) - New From name format(phrase)

These two rewrite options are switched:

Option 5    “List” (on behalf of e-mail) (list_for_email)   
Generates:  From:  "mail-headers Mailing List" (on behalf of \"McLaren, Terry\") <mail-headers@lists.illinois.edu>

Optoin 6    “List” (on behalf of Name) (list_for_name)
Generates:  From: "mail-headers Mailing List" (on behalf of tmclaren@illinois.edu) <mail-headers@lists.illinois.edu>

Looks like a simple type-o fix for the pull down label.

Version
-------
6.2.70

Installation method
-------------------
rpm

Expected behavior
-----------------
“List” (on behalf of e-mail) (list_for_email)   should generate the email
 “List” (on behalf of Name) (list_for_name) shoudl generate a name

Update the pull down menu names to reflect the correct 'from' rewrite.

Actual behavior
---------------
 “List” (on behalf of e-mail) (list_for_email) generates a name label.
“List” (on behalf of Name) (list_for_name) generates an email label.

Steps to reproduce
------------------
Set the appropriate DMARC setting
Send test message
Review message header 

Additional information
----------------------
I'm in the process of characterizing email client behavior for displaying the 'from' field.   Office 2019 vs. O365 vs. Gmail vs. Yahoo.  The MS email clients seem ignore the 'from' header and derive it from other header tags, e.g. sender, X-Original-From.

**Comment by ikedas** [comment] 2023-06-07 21:42
Duplicate of #1498 .

**Closed by ikedas** 2023-06-07 21:42 UTC
Labels: bug
