### ISSUE TITLE
(6.2.16) issues with include_sympa_list via a template?

### ISSUE THREAD

**Issue by agouaux** [sympa-community/sympa#10] opened 2017-04-21 16:21 UTC
I have the following definitions.

/deploy/sympa/etc/data_sources/owner_or_moderator_sympa_list.incl:

`include_sympa_list`
`name owner_or_moderator_sympa_list`
`listname [% param.0 %]`
 
/deploy/sympa/list_data/ecs.bmen.staff/config:

`owner_include`
`profile privileged`
`reception mail`
`source owner_or_moderator_sympa_list`
`visibility conceal`
`source_parameters etech`

However, even though the logic seems to work, get the following in the logs:

Apr 21 10:15:49 aispsympa01 task_manager[35865]: info Sympa::List::_load_include_admin_user_file() 
Bad entry "listname [% param.0 %]" for key "listname", paragraph "include_sympa_list" in 
/deploy/sympa/etc/data_sources/owner_or_moderator_sympa_list.incl

Apr 21 10:15:49 aispsympa01 task_manager[35865]: info Sympa::List::_load_include_admin_user_file() 
Missing key "listname" in param "include_sympa_list" in 
/deploy/sympa/etc/data_sources/owner_or_moderator_sympa_list.incl

**Comment by agouaux** [comment] 2017-04-21 17:48
I just discovered that some of these list config files had *_include paragraphs that were missing the `source_parameters X` line.  In some cases the list had two paragraphs, one with the `source_parameters` line, and another without it.

It turns out, that once my data source for including a list has been selected, if the list owner then wishes to unset that value, there's no way to de-select it.  So what happens is that value is selected, but they deleted the source parameter (the list name), hence the incomplete paragraph and the resulting error messages.

<img width="614" alt="screen shot 2017-04-21 at 12 47 17 pm" src="https://cloud.githubusercontent.com/assets/27364661/25289827/d920369e-2690-11e7-9461-94a1deed175b.png">

**Comment by ikedas** [comment] 2017-04-23 02:35
agouaux,

Latter of your reports already has been filed as a bug.
https://sourcesup.renater.fr/tracker/index.php?func=detail&aid=9972&group_id=23&atid=167

**Comment by ikedas** [comment] 2017-10-13 01:05
So it is a duplicate of the bug fixed after 6.2.16.  This issue is closed by now.

**Closed by ikedas** 2017-10-13 01:05 UTC
Labels: bug, duplicate
