### ISSUE TITLE
List in error_config but don't understand why

### ISSUE THREAD

**Issue by mathieuroquefort** [sympa-community/sympa#835] opened 2019-12-26 11:19 UTC
Hello,

I have recently created a new list. It is the first creation since an upgrade from sympa 6.1.x to 6.2.48. We use families, and I create list through ssh requests : `sympa.pl --add_list familly_name --input_file /etc/sympa/creation/new_list.xml`

This list has been in `error_config` since its creation. But I just can't find why.
I've checked 3 times all the parameters in ‎⁨`etc⁩/sympa⁩/families⁩/familly_name/param_constraint.conf` and compared them with the actual parameters of the list, but they all fit.

The emails received to warn me indicate that I shall look at sympa logs for more information. But in the MySql table 'logs_table', there is nothing about this. All I find here about this list are my accesses to web interface, browsing all config pages to look for the problem.

How can I knom why this list has been set in `error_config` ?
I'm completely stuck...

**Comment by racke** [comment] 2019-12-26 15:49
The 'logs_table' isn't the right place to look for the error messages. Sympa uses syslog: https://sympa-community.github.io/manual/install/configure-system-log.html. The actual location of the log file depends on your setup, but `/var/log/sympa.log` would be a good place to look for.

**Comment by mathieuroquefort** [comment] 2019-12-26 16:34
Thank you.
That's better :)

But all I get there is many times this kind of thing :
`sympa[29689]: err main::#849 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#287 > Sympa::List::set_status_error_config#467 The list Sympa::List <collecteurs29@listes.secourspopulaire.fr> is set in status error_config: no_respect_rules_family(diffusion_interne)`
Without more details.

There is just one thing which seems strange : `sympa[29689]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=create_automatic_list;context=diffusion_interne@listes.secourspopulaire.fr;listname=collecteurs29>`

I'm not sure what this `create_automatic_list` means. We use families, but not automatic families  creation. There is no `automatic_list_families` in sympa.conf...

**Comment by ikedas** [comment] 2019-12-28 01:30
Hi @mathieuroquefort ,

Could you please show us all of your family settings? See the [description on family](https://sympa-community.github.io/manual/customize/basics-families.html) to find necessary settings.

**Comment by mathieuroquefort** [comment] 2019-12-30 08:05
Hello @ikedas,
Thank you for interest.
Here they are.

[config.tt2.txt](https://github.com/sympa-community/sympa/files/4009243/config.tt2.txt)
[edit_list.conf.txt](https://github.com/sympa-community/sympa/files/4009244/edit_list.conf.txt)
[param_constraint.conf.txt](https://github.com/sympa-community/sympa/files/4009245/param_constraint.conf.txt)
[new_diffint_collecteurs29.xml.txt](https://github.com/sympa-community/sympa/files/4009247/new_diffint_collecteurs29.xml.txt)
The last one is the instanciation file.

**Comment by ikedas** [comment] 2019-12-31 07:21
@mathieuroquefort, I couldn't reproduce the problem using your configuration files.

Please show us all the log while sympa.pl was running, i.e. from when you hit the Enter key to when you noticed "error_config" status.

**Comment by mathieuroquefort** [comment] 2019-12-31 09:32
Here it is.
The error_config status comes immediatly, there is nothing before. I've included all the logs about the list during 2 days.
[collecteurs29-2019-12-20.log](https://github.com/sympa-community/sympa/files/4012313/collecteurs29-2019-12-20.log)

**Comment by ikedas** [comment] 2020-01-01 12:33
@mathieuroquefort,
Some log entries seem missing (possiblly due to syslog setting?).

Can you show the `config` file and `config.0` file of collecteurs29 list? I want to compare them with mine.

**Comment by ikedas** [comment] 2020-01-24 01:33
May be a duplicate of #841. Close for the present.

**Closed by ikedas** 2020-01-24 01:33 UTC
Labels: bug, duplicate

**Comment by mathieuroquefort** [comment] 2020-01-27 16:03
Hello,
I'm opening this again because I'm facing the exact same problem.
My hoster solved the problem for collecteurs29 list (I don't know why) but we have the same one now with cfn list. I'd really like to understand what's happening here and not fix it list by list.

Here are all files which may be useful.
[config.txt](https://github.com/sympa-community/sympa/files/4117992/config.txt)
[config.0.txt](https://github.com/sympa-community/sympa/files/4117993/config.0.txt)
[config.tt2.txt](https://github.com/sympa-community/sympa/files/4117995/config.tt2.txt)
[edit_list.conf.txt](https://github.com/sympa-community/sympa/files/4117997/edit_list.conf.txt)
[param_constraint.conf.txt](https://github.com/sympa-community/sympa/files/4117999/param_constraint.conf.txt)

**Comment by mathieuroquefort** [comment] 2020-01-27 16:07
It looks like commenting doesn't re-open the ticket.
Shall I create a new one ?

**Comment by ikedas** [comment] 2020-01-27 18:02
@mathieuroquefort, please see #841. And
- if you think it the different issue, reopen this ticket (#835) and post additional evidence here.
- if you think both the same issue, you need not reopen either.

**Comment by ikedas** [comment] 2020-01-28 03:10
> Hello,
> I'm opening this again because I'm facing the exact same problem.
> My hoster solved the problem for collecteurs29 list (I don't know why) but we have the same one now with cfn list. I'd really like to understand what's happening here and not fix it list by list.
> 
> Here are all files which may be useful.
> [config.txt](https://github.com/sympa-community/sympa/files/4117992/config.txt)
> [config.0.txt](https://github.com/sympa-community/sympa/files/4117993/config.0.txt)
> [config.tt2.txt](https://github.com/sympa-community/sympa/files/4117995/config.tt2.txt)
> [edit_list.conf.txt](https://github.com/sympa-community/sympa/files/4117997/edit_list.conf.txt)
> [param_constraint.conf.txt](https://github.com/sympa-community/sympa/files/4117999/param_constraint.conf.txt)

`config.tt2`:
``` code

[% IF creation_email -%]
  email [% creation_email %]
[% END %]

```
It's broken.  Resulting `config` file will cause error.

**Comment by mathieuroquefort** [comment] 2020-01-28 07:59
Oh.
But what shall I do, then ?
I don't find any explanation about this on https://sympa-community.github.io/manual/customize/basics-families.html
Is it a deprecated parameter ?

**Comment by mathieuroquefort** [comment] 2020-01-28 08:11
Also, this list has been instanciated long ago. config.tt2 is used only during instanciation I think. And many others lists have been instanciated with the same file and are not in error_config.

**Comment by ikedas** [comment] 2020-01-30 01:36
`config.tt2`:
``` code

[% IF creation_email -%]
  email [% creation_email %]
[% END %]

```
Looking at templates bundled in Sympa distribution, it shoud be
``` code

creation
  date_epoch [% creation.date_epoch %]
  date       [% creation.date %]
[% IF creation_email -%]
  email      [% creation_email %]
[% END -%]

```
Recent version of Sympa complains to broken configuration.  Earlier version looks ignoring some unreasonable things.

**Comment by mathieuroquefort** [comment] 2020-02-03 11:33
Hello,

I've downloaded the last source, and in the file `doc⁩/samples⁩/intranet⁩/create_list_templates/ ⁨intranet_list/config.tt2`⁩ I see this :
```
[% IF creation_email -%]
  email [% creation_email %]
[% END %]
```

It is similar to the code that we currently use.
There is no`[% END -%]`

So, I don't understand why you consider my request as "invalid".

Is it the missing
```
creation
  date_epoch [% creation.date_epoch %]
  date       [% creation.date %]
```
?
In the `config` file of a recently created list, I have this :
```
creation
email listmaster@listes.secourspopulaire.fr
date_epoch 1580143634
```
Exactly like for a very old list still worling.
So, it doesn't seem to be a problem.

**Comment by mathieuroquefort** [comment] 2020-02-03 11:34
But maybe the place here to discuss this is not the good one and I should rather write to sympa-users@listes.renater.fr ?

**Comment by mathieuroquefort** [comment] 2020-02-13 16:06
I have finally solved the problem by re-instantiating the list.
I don't know if this `%]` instead of `-%]` was the actual cause. I doubt it, as it is effective only during instantiation.

Some more information explaining why a list is in error would be of great help.
