### ISSUE TITLE
Mailto: link generated by moderate.tt2 template is not interpreted properly in some mail clients

### ISSUE THREAD

**Issue by bboyle262** [sympa-community/sympa#1397] opened 2022-05-10 20:38 UTC
Version
-------
v6.2.68

Installation method
-------------------
Cent7, RPM install, Mariadb, Postfix

Expected behavior
-----------------
E-mails generated by sympa's moderate.tt2 template function should produce a clickable mailto: link to release the message for moderation in all mail clients.

Actual behavior
---------------
Some mail clients, so far tested to occur only on Apple devices, by default do not properly interpret a standalone mailto: URI and seem to require being embedded in an < a href equals> tag to work as expected, which may be better practice formatting for desired cross-platform mail client behavior.

Steps to reproduce
------------------
Send an e-mail to a list set for moderation
Open the moderation e-mail generated by sympa to moderators in MS Outlook for Mac or Apple Mail for iOS, for example
Notice that the following portion of the e-mail generated by sympa is not an expected clickable link in the client:

To distribute the attached message in list brian-testlist2:
mailto:sympa@lists.examplelist.com?subject=DISTRIBUTE%20brian-testlist2%20daddc64c9393405e3de1ce11693d3fc5

Additional information
----------------------

The relevant line in our moderate.tt2 file is as follows:

[% "${conf.email}@${domain}" | mailtourl({subject => "DISTRIBUTE ${list.name} ${modkey}"}) %]

I believe this may be the same bug reported here, still possibly unresolved and in the wild:

https://github.com/sympa-community/sympa/issues/1124

![Screen Shot 2022-05-10 at 3 22 38 PM](https://user-images.githubusercontent.com/98847389/167715381-4bea6144-29c6-44a5-8c72-f0eb9794d1dd.png)

Attached screenshot shows example using Outlook for Mac 16.6 on OSX Monterrey.

This seems to be related with URI handler defaults on Apple devices. We haven't seen any cases where Windows-based clients fail to interpret the mailto: as expected.

**Comment by ikedas** [comment] 2022-05-12 00:27
This issue will be closed as a duplicate of #1124. Please continue on that issue.

**Closed by ikedas** 2022-05-12 00:27 UTC
