### ISSUE TITLE
Anyone can unsubscribe a member of a list with open scenario

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#233] opened 2018-03-14 18:53 UTC
Debian Stretch 9.4 and Sympa Package 6.2.16 environment.

I have one list (list@lists.domain.org) configured with unsubscribe.open scenario:

```
title.gettext open

!is_subscriber ([listname],[email]) smtp,dkim,smime,md5 -> do_it
!equal ([sender],[email])           smtp,dkim           -> request_auth([email])
true()			            smtp,md5,smime      -> do_it
```

and three users: user_a@domain.org, user_b@domain.org and user_c@domain.org Both users A and B are members of the list, while user C is not.

When either user A (member) or user C (not member) sends a message to sympa@lists.domain.org with the following subject "SIGNOFF list@domain.org user_b@domain.org" then user B is automatically unsubscribed from the list. The expected behaviour should be user B to receive an authentication request, but it doesn't happen. 

Thank you very much. Regards.

**Comment by ikedas** [comment] 2018-03-26 07:33
Hi @qosobrin,

Can you also check recent version of Sympa?

**Comment by qosobrin** [comment] 2018-03-26 15:36
I have just checked with version 6.2.30 and the problem continues. When user A sends the SIGNOFF message to the list "SIGNOFF list@domain.org user_b@domain.org" User B is unsubscribed from the list. The funny thing is that User B receives the unsubscription mail notification.

**Comment by qosobrin** [comment] 2018-03-26 19:24
After editing the unsubscribe.open scenario and removing the ! sign in the second line:
```
title.gettext open

!is_subscriber ([listname],[email]) smtp,dkim,smime,md5 -> do_it
equal ([sender],[email])           smtp,dkim           -> request_auth([email])
true()			            smtp,md5,smime      -> do_it
```
I tried again and this time user B received the unsubscription confirmation request. It seems like either the equal scenario condition is returning the opposite value or the ! sign is not being  evaluated correctly.

**Comment by ikedas** [comment] 2018-03-29 08:03
Hi @qosobrin,

Can you show sympa log during original scenario is processed? (Log lines not including "`Sympa::Scenario::" are not needed.)

**Comment by qosobrin** [comment] 2018-03-29 20:44
Find attached the full log (debug 3) during user signoff ([issue_233.log](https://github.com/sympa-community/sympa/files/1861886/issue_233.log)). In this case I include both sympa and postfix logs. The particular lines referring to the scenario processing are these ones:
```
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::_parse_scenario(tracking, default, listas.usc.es)
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::request_action(Sympa::List <lista-probas@listas.usc.es>, unsubscribe, smtp, HASH, )
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::new()
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::new()
Mar 29 22:31:11 parasito sympa_msg[815]: debug Sympa::Scenario::new() Unable to read file /home/sympa/var/lib/sympa/list_data/lista-probas/scenari/include.unsubscribe.header
Mar 29 22:31:11 parasito sympa_msg[815]: debug Sympa::Scenario::new() Unable to read file /home/sympa/etc/listas.usc.es/scenari/include.unsubscribe.header
Mar 29 22:31:11 parasito sympa_msg[815]: debug Sympa::Scenario::new() Unable to read file /home/sympa/etc/scenari/include.unsubscribe.header
Mar 29 22:31:11 parasito sympa_msg[815]: debug Sympa::Scenario::new() Unable to read file /home/sympa/share/sympa/default/scenari/include.unsubscribe.header
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::verify(HASH, !is_subscriber ([listname],[email]), HASH, )
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::verify(HASH, !equal ([sender],[email]), HASH, )
Mar 29 22:31:11 parasito sympa_msg[815]: debug2 Sympa::Scenario::verify(HASH, true(), HASH, )
```
Should you need anything else, do not hesitate to ask me.

Thank you very much.
Regards.

**Comment by ikedas** [comment] 2018-04-02 01:29
Hi @qosobrin,

According to log, sender of message bound for `sympa@lists.domain.org` looks `member@domain.org` and sent command looks "`SIGNOFF member@domain.org`".  Is it right?

**Comment by ikedas** [comment] 2018-04-02 03:20
Hi @qosobrin,

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/246.patch) and check if the problem is solved?

Additionally if possible, could you please check if other scenarios containing `[email]` work properly.

**Comment by qosobrin** [comment] 2018-04-03 21:55
Hi, @ikedas:

I tried your patch with the unsubscribe scenario and it works as expected. 

member@domain.org sent an unsubscribe message with subject ```SIGNOFF list outsider@domain.org``` to the sympa email address and outsider@domain.org received the confirmation request without being removed from the list. Moreover, the confirmation request works and when used removes the user from the list.

The only other scenario that uses [email] is move_user.auth, but I did not try it because I do not know where it is used. If you could give me hint I will try it and let you know.

Thank you very much for your good work.

Regards,

**Comment by ikedas** [comment] 2018-04-04 00:49
Hi @qosobrin,

`move_user` scenario is used on:
  - As a listmaster, "Changing user's email" of "Users" in "Listmaster Admin Menu"
  - As a user, "Changing your email address" in "User preferences"

**Comment by qosobrin** [comment] 2018-04-04 20:03
OK, I tried to move an user email, since there is no mail command to carry it out I did it through the web interface, and worked as expected. My sympa was configured with the default value of the move_user variable, in this case, move_user.auth

```
equal([sender],[current_email])     smtp,dkim,md5,smime -> request_auth([email])
is_listmaster([sender])             md5,smime           -> do_it
equal([sender],[email])             md5,smime           -> do_it
true()                              smtp,dkim,md5,smime -> reject
``` 

I logged in with account userA@domain.org and changed the email address to userB@domain.org. userB@domain.org received an auth request email. After using the auth url the email changed.

On a side note to this, I do not see the point of the third line in this scenario:

```
equal([sender],[email])             md5,smime           -> do_it
``` 

Can anyone explain me how come sender and email can be the same when this action can only be carried out in a web interface? I understand that email refers to the new email address, while current_email refers to the email address the user had when he logged in (that, of course, should be equal to the sender, except when the change is carried out by the listmaster). If everything that I said is true then the third line will never be evaluated, so there is no need to include it in this scenario. Please, correct me if I'm wrong.

Regards.

**Comment by ikedas** [comment] 2018-04-05 04:13
Hi @qosobrin,

Since `/sympa/move_user` itself can accessed by any authenticated user, the third rule may be carried out.  However, I feel what is performed is weird.

**Comment by qosobrin** [comment] 2018-04-06 08:43
@ikedas I have nothing more to add to this issue. Feel free to close it when you consider.

**Comment by ikedas** [comment] 2018-04-11 07:37
Merged.

**Closed by ikedas** 2018-04-11 07:37 UTC
Labels: bug
