### ISSUE TITLE
sympa fake upgrade on sympa 6.2.40 (from 6.1.17) on debian 10 stable

### ISSUE THREAD

**Issue by bv-unibs** [sympa-community/sympa#705] opened 2019-07-19 06:29 UTC
Hi,
This is related to the issue described in:

https://github.com/sympa-community/sympa/issues/530

After doing the fake upgrade procedure successfully on testing server from sympa 6.1.17 to sympa 6.2.38, like reported in the issue above, I'm trying to repeat the same procedure on the production server with debian 10 stable:

./sympa.pl --upgrade --from=6.1.17 --to=6.2.40

Now I've tried to fake upgrade from 6.1.17 to 6.2.40 and the fake upgrade terminates with errors.

These are the errors I've received after the script was done:

notice Sympa::Upgrade::upgrade() Upgrading admin_table
err main::#890 > Sympa::Upgrade::upgrade#1835 > Sympa::DatabaseDriver::MySQL::delete_field#288 > Sympa::Database::do_query#280 Unable to execute SQL statement "ALTER TABLE admin_table DROP COLUMN `date_admin`": (42000) Can't DROP COLUMN `date_admin`; check that it exists
err main::#890 > Sympa::Upgrade::upgrade#1835 > Sympa::DatabaseDriver::MySQL::delete_field#296 Could not delete field date_admin from table admin_table in database sympa
notice Sympa::Upgrade::upgrade() Upgrading subscriber_table
err main::#890 > Sympa::Upgrade::upgrade#1838 > Sympa::DatabaseDriver::MySQL::delete_field#288 > Sympa::Database::do_query#280 Unable to execute SQL statement "ALTER TABLE subscriber_table DROP COLUMN `date_subscriber`": (42000) Can't DROP COLUMN `date_subscriber`; check that it exists
err main::#890 > Sympa::Upgrade::upgrade#1838 > Sympa::DatabaseDriver::MySQL::delete_field#296 Could not delete field date_subscriber from table subscriber_table in database sympa

Can you help understand how can I avoid these errors, or If I can ignore them? 

thanks

**Comment by ikedas** [comment] 2019-07-19 06:50
Duplicate of #600.

**Closed by ikedas** 2019-07-19 06:50 UTC
Labels: duplicate
