### ISSUE TITLE
bulk.pl dies if I try to increase bulk_max_count 

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1248] opened 2021-10-12 07:37 UTC
Version
-------
6.2.66

Installation method
-------------------
My own rpm, derived from "official" Redhat rpm.

Expected behavior
-----------------

bulk.pl should run one parent and up to six child processes (rather than the default one parent and three children) if I set
```bulk_max_count = 6``` in sympa.conf.

Actual behavior
---------------
The parent bulk.pl dies with:

```
Oct  8 08:32:42 lists-1 bulk[34718]: err main::#160 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessOutgoing::_twist#422 > Sympa::Mailer::store#118 DIED: Illegal division by zero at /usr/share/sympa/lib/Sympa/Mailer.pm line 118.
```
as soon a message is delivered for bulk.pl to process. That appears to be:
```
    my $maxsmtp =
        int($Conf::Conf{'maxsmtp'} / ($self->{redundancy} || 1)) || 1;
```
although I can't immediately see how ```$self->{redundancy} || 1``` can evaluate as zero

**Comment by racke** [comment] 2021-10-12 07:50
You are using the default value for _maxsmtp_?

**Comment by ikedas** [comment] 2022-04-15 01:26
@dpc22, is this problem recurring? If not, it could be a less reproducible problem such as hardware malfunction. I'd like to close this issue for the moment.

**Comment by dpc22** [comment] 2022-04-15 07:12
It is unlikely to have been hardware failure (the machine runs on a large VM farm).

However CPU load really isn't an issue ever since I discovered that all of the CPU load on the system was caused by a bug in Exim reading messages from stdin. The system is effectively idle now. (Memory load is another story).

Please close the ticket. It is unlikely that I am going to tinker with these settings in future.

**Comment by ikedas** [comment] 2022-04-15 22:25
It seems to have something to do with the cause.

@dpc22 , thank you for sharing your experiences! Close without any fixes.

**Closed by ikedas** 2022-04-15 22:25 UTC
Labels: bug
