### ISSUE TITLE
Noise in Apache error_log

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1325] opened 2022-01-18 07:09 UTC
Version
-------

6.2.66

Installation method
-------------------

My own rpm, derived from offical rpm

Expected behavior
-----------------

Apache error log should be empty

Actual behavior
---------------

There is some noise about some uninitialized values.

Additional information
----------------------

```
[Mon Jan 17 07:49:57.545607 2022] [proxy_fcgi:error] [pid 56764] [client XXX.XXX.XXX.XXX:64078] AH01071: Got error 'Use of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse ', referer: https://lists.cam.ac.uk/sympa/review/XXX/owner

[Mon Jan 17 07:49:57.545833 2022] [proxy_fcgi:error] [pid 56764] [client XXX.XXX.XXX.XXX:64078] AH01071: Got error 'ninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of unini', referer: https://lists.cam.ac.uk/sympa/review/XXX/owner

[Tue Jan 18 00:07:52.655029 2022] [proxy_fcgi:error] [pid 13020] [client YYY.YYY.YYY.YYY:42672] AH01071: Got error 'Use of uninitialized value in string eq at /usr/share/sympa/lib/Conf.pm line 817.\n', referer: https://lists.cam.ac.uk/sympa/review/YYY
```

The first two of these always seem to appear at the same time, triggered by a single http request.

The third is separate and appears to be something to do with the SSO subsystem

**Comment by ikedas** [comment] 2022-01-22 06:17
There may be the other noisy log entries.  If there are others, please list them here.  When you have listed enough logs, please let us know.

**Comment by laerm** [comment] 2022-05-23 08:46
I'm on v6.2.68 and seeing the same errors. I also am getting a few of the following: 

`[Mon May 23 10:27:50 2022] [error] [pid 21719] mod_proxy_fcgi.c(851): [client XXX.XXX.XXX.XXX:50630 AH01071: Got error 'ninitialized value $owner_domain in concatenation (.) or string at /usr/share/sympa/lib/Sympa/List/Users.pm line 66.\nUse of uninitialized value $owner_domain in pattern match (m//) at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.\n'`

**Comment by laerm** [comment] 2022-05-25 10:51
I'm also seeing these errors on v6.2.68. And when trying to add a privileged user, I get the above mentioned errors and the following one:

`[Wed May 25 12:35:31 2022] [error] [pid 1915] mod_proxy_fcgi.c(851): [client 10.232.4.10:57748 AH01071: Got error 'ninitialized value $owner_domain in concatenation (.) or string at /usr/share/sympa/lib/Sympa/List/Users.pm line 66.\nUse of uninitialized value $owner_domain in pattern match (m//) at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.\n'`

The user is added as owner, but not a privileged one.

**Comment by qosobrin** [comment] 2022-06-10 09:59
In issue #1414 I mentioned the appearance of this line in apache error log:

```
[Fri Jun 10 10:01:20.138070 2022] [proxy_fcgi:error] [pid 70601:tid 140264135964416] [client 192.168.23.18:58413] AH01071: Got error [Fri Jun 10 10:01:20 2022] wwsympa.fcgi: Use of uninitialized value in concatenation (.) or string at /usr/share/sympa/default/web_tt2/search_user.tt2 line 48.\n', referer: http://sympa-prepro.domain.com/wws/serveradmin/users
```

They are related with user searching and the attempt to display an empty string. I proposed the change of the following line in `web_tt2/search_user.tt2` to correct the problem:

```
[%|optdesc('reception')%][% l.value.reception %][% END %]
```

to:

```
[% IF l.value.reception %][%|optdesc('reception')%][% l.value.reception %][% END %] [% END %]
```

My solution is tested to correct the problem but not fully tested to know if it breaks any other thing but I guess it should be safe.

There is a Debian bug report for this error since April 2017 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860807), so if it is corrected the Debian bug report should also be updated. This error was already present in 6.2.16 (from Debian Stretch).

Thank you very much. 
Best regards.

**Comment by qosobrin** [comment] 2022-06-10 19:04
> I'm also seeing these errors on v6.2.68. And when trying to add a privileged user, I get the above mentioned errors and the following one:
> 
> `[Wed May 25 12:35:31 2022] [error] [pid 1915] mod_proxy_fcgi.c(851): [client 10.232.4.10:57748 AH01071: Got error 'ninitialized value $owner_domain in concatenation (.) or string at /usr/share/sympa/lib/Sympa/List/Users.pm line 66.\nUse of uninitialized value $owner_domain in pattern match (m//) at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.\n'`
> 
> The user is added as owner, but not a privileged one.

Three points here:

1. I can see these errors also in 6.2.60, but in 6.2.60 the privileged admin is added. 
2. I can also point that the errors in 6.2.60 seem to be related to pressing the "Apply modifications" button in the Owners section, even if there is no change to apply. Pressing the same button in the Editors section does not trigger the errors.
3. And finally, these errors are weird since every line seems to contain other errors, like the result of a function passing errors to another function instead of a valid value.

Best regards.
Luis A.

**Comment by ikedas** [comment] 2022-12-01 13:12
I’ll address the noises reported so far and close this issue by the end of this year.

**Comment by ikedas** [comment] 2024-04-24 13:52
https://github.com/sympa-community/sympa/issues/1325#issue-1106550151
> ```
> [Wed Apr 24 13:35:04.025147 2024] [proxy_fcgi:error] [pid 408221] [client 2a02:8109:b5a3:…:X] AH01071: Got error '[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n'
> ```

**Comment by paulmenzel** [comment] 2024-04-24 13:56
Did you re-open the issue, because it should be fixed in *sympa* 6.2.70~dfsg-2 in Debian GNU/Linux 12 (bookworm), and it isn’t, or to somehow back port it to Debian’s version?

As written in https://github.com/sympa-community/sympa/issues/1828, in my case, the loading even failed. I took the URL from the browser history, so no idea, if some parameter was present for the URL.

**Comment by ikedas** [comment] 2024-04-24 14:33
If you want the problem to be fixed on Debian package, please submit a report to the Debian project.  This project deals with Sympa in general.
And I thought the connection timeout you observed has not been caused by Sympa and it's a noise in error_log, isn't it?

**Comment by ikedas** [comment] 2024-04-25 04:04
@paulmenzel ,
It is natural to assume that the reason page loading error information is not recorded in the logs of Sympa server is because it was not caused by Sympa. You are probably just assuming that the other logs closer in time are related to the event you observed.

First, please check to see if the same logs were being output when the event you observed was not occurring (they probably were). Second, please apply the PR above and see if the logs are no longer being output.

**Closed** 2024-09-06 23:55 UTC
Labels: bug
