### ISSUE TITLE
`wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.`

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#1828] opened 2024-04-24 13:41 UTC
Using Debian GNU/Linux 12 (bookworm) with *sympa* 6.2.70~dfsg-2, loading a https://listen.example.net/sympa/review/somelist without being logged in, the brower aborted loading the page after one or two seconds with the message the connection timed out. The HTTP Web server logs contain:

    [Wed Apr 24 13:35:04.025147 2024] [proxy_fcgi:error] [pid 408221] [client 2a02:8109:b5a3:…:X] AH01071: Got error '[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n'

After reloading the URL, that means trying again, it worked.

Do you have an idea, what is going on?

**Comment by ikedas** [comment] 2024-04-24 13:48
A duplicate of #1325 .

**Closed** 2024-04-24 13:52 UTC
Labels: bug, duplicate

**Comment by paulmenzel** [comment] 2024-04-24 15:13
Some more logs:

`access.log`:

    2a02:8109:b5a3:6600:… - - [24/Apr/2024:13:34:57 +0000] "GET /sympa/review/X HTTP/1.1" 200 4017 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
    2a02:8109:b5a3:6600:… - - [24/Apr/2024:13:35:01 +0000] "GET /sympa/review/X HTTP/1.1" 200 4017 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
    2a02:8109:b5a3:6600:… - - [24/Apr/2024:13:35:04 +0000] "GET /static-sympa/js/jqplot/jquery.jqplot.css?v1.0.8 HTTP/1.1" 200 2373 "https://listen.vocantare.de/sympa/review/X" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"

`error.log`:

    [Wed Apr 24 13:35:01.920966 2024] [proxy:debug] [pid 408221] proxy_util.c(3086): [client 2a02:8109:b5a3:6600:…:38772] AH00944: connecting fcgi:///home/www/listen.vocantare.de to :8000
    [Wed Apr 24 13:35:01.920973 2024] [proxy:debug] [pid 408221] proxy_util.c(3153): [client 2a02:8109:b5a3:6600:…:38772] AH02545: fcgi: has determined UDS as /run/sympa/wwsympa.socket (for :8000)
    [Wed Apr 24 13:35:01.920976 2024] [proxy:debug] [pid 408221] proxy_util.c(3294): [client 2a02:8109:b5a3:6600:…:38772] AH00947: connecting /home/www/listen.vocantare.de to /run/sympa/wwsympa.socket:0 (:8000)
    [Wed Apr 24 13:35:01.921032 2024] [proxy:debug] [pid 408221] proxy_util.c(3676): AH02823: FCGI: connection established with Unix domain socket /run/sympa/wwsympa.socket (:8000)
    [Wed Apr 24 13:35:01.921071 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of Require all granted: granted 
    [Wed Apr 24 13:35:01.921075 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of <RequireAny>: granted 
    [Wed Apr 24 13:35:02.052075 2024] [ssl:debug] [pid 408680] ssl_engine_io.c(1146): [client 2a02:8109:b5a3:6600:…:38758] AH02001: Connection closed to child 1 with standard shutdown (server listen.vocantare.de:443)
    [Wed Apr 24 13:35:04.025147 2024] [proxy_fcgi:error] [pid 408221] [client 2a02:8109:b5a3:6600:…:38772] AH01071: Got error '[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n'
    [Wed Apr 24 13:35:04.025323 2024] [deflate:debug] [pid 408221] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38772] AH01384: Zlib: Compressed 11090 to 2940 : URL /sympa/review/X
    [Wed Apr 24 13:35:04.025432 2024] [proxy:debug] [pid 408221] proxy_util.c(2700): AH00943: FCGI: has released connection for (*:80) 
    [Wed Apr 24 13:35:04.253901 2024] [ssl:debug] [pid 409253] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38770] AH02034: Initial (No.1) HTTPS request received for child 10 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.254237 2024] [ssl:debug] [pid 408221] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38772] AH02034: Subsequent (No.2) HTTPS request received for child 5 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.271350 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.271378 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.272431 2024] [deflate:debug] [pid 409253] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38770] AH01384: Zlib: Compressed 5624 to 1352 : URL /static-sympa/js/jqplot/jquery.jqplot.css, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.300930 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.300965 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.302713 2024] [deflate:debug] [pid 408221] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38772] AH01384: Zlib: Compressed 37683 to 8736 : URL /static-sympa/js/jquery-ui/jquery-ui.css, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314437 2024] [ssl:debug] [pid 409253] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38770] AH02034: Subsequent (No.2) HTTPS request received for child 10 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314521 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314527 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X 
    [Wed Apr 24 13:35:04.320860 2024] [deflate:debug] [pid 409253] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38770] AH01384: Zlib: Compressed 172482 to 42083 : URL /static-sympa/js/jqplot/jquery.jqplot.min.js, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:02.052075 2024] [ssl:debug] [pid 408680] ssl_engine_io.c(1146): [client 2a02:8109:b5a3:6600:…:38758] AH02001: Connection closed to child 1 with standard shutdown (server listen.vocantare.de:443)
    [Wed Apr 24 13:35:04.025147 2024] [proxy_fcgi:error] [pid 408221] [client 2a02:8109:b5a3:6600:…:38772] AH01071: Got error '[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n[Wed Apr 24 13:35:03 2024] wwsympa.fcgi: Use of uninitialized value $args[0] in pattern match (m//) at /usr/share/sympa/lib/Sympa/Scenario.pm line 1164.\n'
    [Wed Apr 24 13:35:04.025323 2024] [deflate:debug] [pid 408221] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38772] AH01384: Zlib: Compressed 11090 to 2940 : URL /sympa/review/X
    [Wed Apr 24 13:35:04.025432 2024] [proxy:debug] [pid 408221] proxy_util.c(2700): AH00943: FCGI: has released connection for (*:80)
    [Wed Apr 24 13:35:04.253901 2024] [ssl:debug] [pid 409253] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38770] AH02034: Initial (No.1) HTTPS request received for child 10 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.254237 2024] [ssl:debug] [pid 408221] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38772] AH02034: Subsequent (No.2) HTTPS request received for child 5 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.271350 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.271378 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.272431 2024] [deflate:debug] [pid 409253] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38770] AH01384: Zlib: Compressed 5624 to 1352 : URL /static-sympa/js/jqplot/jquery.jqplot.css, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.300930 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.300965 2024] [authz_core:debug] [pid 408221] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38772] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X 
    [Wed Apr 24 13:35:04.302713 2024] [deflate:debug] [pid 408221] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38772] AH01384: Zlib: Compressed 37683 to 8736 : URL /static-sympa/js/jquery-ui/jquery-ui.css, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314437 2024] [ssl:debug] [pid 409253] ssl_engine_kernel.c(415): [client 2a02:8109:b5a3:6600:…:38770] AH02034: Subsequent (No.2) HTTPS request received for child 10 (server listen.vocantare.de:443), referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314521 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of Require all granted: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.314527 2024] [authz_core:debug] [pid 409253] mod_authz_core.c(815): [client 2a02:8109:b5a3:6600:…:38770] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.vocantare.de/sympa/review/X
    [Wed Apr 24 13:35:04.320860 2024] [deflate:debug] [pid 409253] mod_deflate.c(909): [client 2a02:8109:b5a3:6600:…:38770] AH01384: Zlib: Compressed 172482 to 42083 : URL /static-sympa/js/jqplot/jquery.jqplot.min.js, referer: https://listen.vocantare.de/sympa/review/X

There is nothing about the access from 13:34:57 there, so maybe it is a client error. Anyway, very strange.

**Comment by ikedas** [comment] 2024-04-24 23:28
Is there an access log *after* the log in question? Access log is written when the response has been completed.
