### ISSUE TITLE
LDAP default settings for verify

### ISSUE THREAD

**Issue by popindavibe** [sympa-community/sympa#143] opened 2017-12-16 12:07 UTC
Hi all,
I spent a quite some time changing my filters after upgrade to Sympa 6.2

In the end I figured out thanks to sympa logs that the issue came from the `ca_verify`  option which was marked as required/ optional and which **does not** allow you to specify where your CA actually is.  
So all my testing locally was fine because of my CA being set up in /etc/ldap/ldap.conf, and my authentication was also fine because you can specify your CA there as well, but it looks like for data source setup there is no way to set your own CA file for it. Which means my TLS connection has to be set for **none** related to `ca_verify`.

Is this a feature or can we hope that this will be implemented in future updates? Maybe there is already a way, in which case I would very much obliged if you can point me to it.

**Comment by ikedas** [comment] 2017-12-20 10:48
looks like a duplicate of the bug (hopefully) fixed by #116.

**Comment by popindavibe** [comment] 2017-12-24 12:26
I am not sure if this is the same issue. I was mostly underlying the fact that we can specify a CA file and enforce verification in auth.conf while this is not a possibility at all when configuring ldap list filters to be used for mailing lists.

**Comment by ikedas** [comment] 2017-12-25 04:01
@popindavibe, can you show the settings both of `auth.conf` and "ldap list filters"?

**Comment by ikedas** [comment] 2018-08-16 10:07
Stagnated issue. Closed for the present.

**Closed by ikedas** 2018-08-16 10:07 UTC
Labels: bug, duplicate, wontfix
