### ISSUE TITLE
Scenario names with dots generate errors  (Sympa 6.2.42)

### ISSUE THREAD

**Issue by ogermes** [sympa-community/sympa#599] opened 2019-04-18 11:37 UTC
Scenario names with dots generate errors, examples :

- dot in the name of visibility scenario 
DIED: Can't call method "authz" on an undefined value at /usr/local/sympa/bin/wwsympa.fcgi line 2887.
 at /usr/local/sympa/bin/wwsympa.fcgi line 2887.
    main::check_param_out() called at /usr/local/sympa/bin/wwsympa.fcgi line 1590

- dot in the name of subscribe scenari 
DIED: Can't call method "authz" on an undefined value at /usr/local/sympa/bin/wwsympa.fcgi line 2679.
 at /usr/local/sympa/bin/wwsympa.fcgi line 2679.
    main::check_param_in() called at /usr/local/sympa/bin/wwsympa.fcgi line 1517

-------

Sympa version 6.2.42
Installation method
-------------------

Install from source package

Expected behavior
-----------------

No error, or prohibit scenario names with a dot

---------------

Additional information
----------------------
I have checked that renaming the scenario solves the problem.

**Comment by ikedas** [comment] 2019-04-18 11:39
Duplicate of #589.

**Closed by ikedas** 2019-04-18 11:39 UTC
