### ISSUE TITLE
Meaningful error message should be shown for unauthenticated reviewbouncing page

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#1692] opened 2023-06-27 06:54 UTC
Version
-------
6.2.72

Installation method
-------------------
Release tarball

Expected behavior
-----------------
When going to https://example.org/sympa/reviewbouncing/list while being unauthenticated, I should get a "You need to login" message.

Actual behavior
---------------
I have a red box, used for error messages, but with no error message in it.

Steps to reproduce
------------------
Go to https://example.org/sympa/reviewbouncing/list while being not authenticated

Additional information
----------------------
Here’s the relevant wwsympa’s log:
```
notice Sympa::Scenario::do_verify_custom() Using previous custom condition cache nobody
info main::check_action_parameters() [robot example.org] [session 91800303784794] [client 2001:db8::100] [list tock] Authorization failed, insufficient privileges
err main::#1547 [robot example.org] [session 91800303784794] [client 2001:db8::100] Missing required parameters for action "reviewbouncing"
```

**Comment by ikedas** [comment] 2023-06-27 07:05
Duplicate of #1487 .

**Comment by racke** [comment] 2023-06-27 07:12
Even if you get an error message it is not user friendly and confusing. It is better to redirect to the login with a friendly message like "Please login to review the bounces for list xyz.". So I suggest to close https://github.com/sympa-community/sympa/issues/1487 and reopen this issue.

**Comment by adam12b1** [comment] 2024-04-11 18:19
+1

We are running into the same bug, but it is not just in this specific case - it happens in many different "access denied" cases, in fact I believe it is most cases.

For example: Login as a moderator, but not an owner. Try to access any of the list settings pages, many of which are still available in the nav menu. You always get the same empty red dialog box.

**Comment by ikedas** [comment] 2024-04-13 11:21
Please apply [this patch](https://github.com/sympa-community/sympa/commit/6b3d356538f97dbaff975aa00c0c0ac3b457acbc.patch) (against 6.2.72) and check if the problem will be solved.

**Comment by adam12b1** [comment] 2024-04-16 17:55
Sorry to say, the patch had no effect, at least on the specific case we're seeing. (Login as an editor but not an owner, try to access any list settings pages.) I did not test any other cases.

**Comment by ikedas** [comment] 2024-04-17 09:38
@adam12b1 , please apply [this additional patch](https://github.com/sympa-community/sympa/commit/40b9622203a9459045450e566f0803132b3fdd38.patch) and try again.

**Comment by adam12b1** [comment] 2024-04-22 19:34
Hooray, looks like that fixed it, thanks!

**Closed** 2024-04-26 09:46 UTC
Labels: bug
