### ISSUE TITLE
error_performing_condition in scenario

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#836] opened 2019-12-27 21:10 UTC
I get the error error_performing_condition when I manage a list
See the log file:

[logfile.txt](https://github.com/sympa-community/sympa/files/4006249/logfile.txt)

Version
-------

Sympa version 6.2.52

Installation method
-------------------

From source

Expected behavior
-----------------

No error

Actual behavior
---------------
As said: an error_performing_condition

Additional information
----------------------
The content of send.private is the default one
[send.private.txt](https://github.com/sympa-community/sympa/files/4006256/send.private.txt)

**Comment by ikedas** [comment] 2019-12-28 01:18
Hi @pascalmaes,

Sympa/Scenario.pm in your Sympa looks modified.  Please rewind all of your changes and check if the problem will be reproduced.

**Comment by pascalmaes** [comment] 2019-12-28 08:06
It is not as I have installed the version 6.2.52 from the sources:

- configure
- make
- make install
- cpanm --installdeps --with-recommends .
- /var/sympa/bin/sympa.pl --upgrade

# diff sympa-6.2.52/src/lib/Sympa/Scenario.pm /var/sympa/bin/Sympa/Scenario.pm
#
# ls -l /var/sympa/bin/Sympa/Scenario.pm
-rw-r--r-- 1 root root 58717 Dec 27 16:51 /var/sympa/bin/Sympa/Scenario.pm

**Comment by ikedas** [comment] 2019-12-28 10:00
I don’t know why Sympa was installed under /bar/sympa instead of /home/sympa without “—prefix” configure option.

BTW do you filter the log? If you did, please show us entire logs.

**Comment by pascalmaes** [comment] 2019-12-29 09:45
Here is the script I"m using to configure Sympa:
[configure.txt](https://github.com/sympa-community/sympa/files/4007937/configure.txt)

I give the log file from the starting of Sympa and Apache2 to the error

**Comment by pascalmaes** [comment] 2020-01-18 09:49
Hello,


The problems comes from the scenario include.send.header
It contains:

equal([is_bcc], 1)	smtp,dkim,md5,smime -> request_auth

If I delete the scenario, all is going well; if the scenario exists, I have the error:

Jan 18 10:46:40 sympa-test.sipr.ucl.ac.be wwsympa[28411]: info Sympa::Scenario::authz() Error in scenario Sympa::Scenario <send.newsletter;/var/sympa/default/scenari/send.newsletter>, context Sympa::List <test-sympa-4@listes.uclouvain.be>: (error-performing-condition)

**Comment by pascalmaes** [comment] 2020-01-18 10:07
The problem is related to "is_bcc".

If I don't use the include; send.header scénario but I choose the public_nobcc, I have the same error:

Jan 18 11:05:45 sympa-test.sipr.ucl.ac.be wwsympa[30460]: info Sympa::Scenario::authz() Error in scenario Sympa::Scenario <send.public_nobcc;/var/sympa/default/scenari/send.public_nobcc>, context Sympa::List <test-sympa-4@listes.uclouvain.be>: (error-performing-condition)

**Comment by pascalmaes** [comment] 2020-01-19 09:44
To be sure, I have reinstall Sympa 6.2.52 from nothing:

# ./configure \
--prefix=/var/sympa \
--with-confdir=/etc/sympa \
--with-perl=/usr/bin/perl \
--with-user=sympa \
--with-group=sympa \
--with-postalias=/usr/sbin/postalias \
--with-postmap=/usr/sbin/postmap

# make
# make install

I create a list (newsletter) and the I change the sending mode to public_nobcc; you will fin de log file as attachment
[sympalog.txt](https://github.com/sympa-community/sympa/files/4082467/sympalog.txt)

**Comment by ikedas** [comment] 2020-01-20 02:15
Reported problem is slightly similar to #841  (though I don't know why "err" log entries aren't shown your bug report).  @pascalmaes, could you please apply [this patch](https://github.com/sympa-community/sympa/commit/182d6e75b81a75686d81651aba34fc82a403f659.patch), restart Sympa services and web service and check if the problem will be solved?

**Comment by pascalmaes** [comment] 2020-01-20 07:14
Hello,


It works fine with the patch.

Thanks

**Comment by ikedas** [comment] 2020-01-20 08:58
Thanks for confirming! This issue is closed as a duplicate of #841.

**Closed by ikedas** 2020-01-20 08:58 UTC
Labels: bug, duplicate
