### ISSUE TITLE
moderation UI doesn't allow mass operations

### ISSUE THREAD

**Issue by mhow2** [sympa-community/sympa#122] opened 2017-11-16 09:14 UTC
Hi,
I am refering to this post (and their replies) https://listes.renater.fr/sympa/arc/sympa-fr/2017-01/msg00005.html

It is a regression from the previous versions of sympa and very annoying when it's needed to delete hundred of spam messages from the UI.

At some point the UI could provide a way to "moderate selected messages, reject others"

Regards,

**Comment by sivertkh** [comment] 2017-11-16 09:42
+1 Out users complain about this as well.

**Comment by ikedas** [comment] 2017-11-16 10:23
wwsympa.fcgi itself accepts multiple items to process.  If templates are changed appropriately, requested feature will be realized.  Issue #27 is alike.

PR is awaited.

**Comment by mhow2** [comment] 2017-11-16 10:34
@ikedas : as it is a regression, maybe we can take a look to what was the template before ? Could you lead potential contributors to the related files to alter ?

**Comment by ikedas** [comment] 2017-11-17 02:12
@mhow2, The template is `web_tt2/modindex.tt2`. Its content has been changed during development of 6.2.

**Comment by mhow2** [comment] 2017-11-24 09:27
@ikedas : to be perfectly clear, from who do we wait a PR ? Is this bug going to be processed by the core team or by contributors ? I'm totally new with templating in sympa, I think it could go way faster with someone used to it. @dverdin maybe ?

**Comment by l4uc3** [comment] 2017-12-14 10:04
Hi everyone,
We had the same pb in university of Strasbourg. We changed the modindex.tt2 to improve the mass moderation. Enclosed is the modindex.tt2 we use.
[modindex.tt2.gz](https://github.com/sympa-community/sympa/files/1558628/modindex.tt2.gz)
I added a pull request with the file. Up to you to merge it.
Have a good one !
Laurence

**Comment by dverdin** [comment] 2017-12-14 13:52
Thanks Laurence!
This was becoming worrying...
It's good to see you back to Sympa contribution, by the way. ;-)

**Comment by ikedas** [comment] 2017-12-16 07:06
Hi @l4uc3,
  * By your modification ``<form>`` elements are nested. Standards says this element should be "[with no form element descendants](https://www.w3.org/TR/2017/REC-html52-20171214/sec-forms.html#the-form-element)".
  * On 6.1.x, it was sometimes reported that, with a form including a table having many (20, 30 or so) rows, some of checkboxes were omitted, and not all selected messages were distributed/rejected.

**Comment by l4uc3** [comment] 2017-12-16 19:18
Hello,


On 16/12/2017 08:06, IKEDA Soji wrote:
>
> Hi @l4uc3 <https://github.com/l4uc3>,
>
>   * By your modification |<form>| elements are nested. Standards says
>     this element should be "with no form element descendants
>     <https://www.w3.org/TR/2017/REC-html52-20171214/sec-forms.html#the-form-element>".
>
I was careful not to put a form inside a form. Could you point me inside 
the code where you see a nested element ?
>
>   * On 6.1.x, it was sometimes reported that, with a form including a
>     table having many (20, 30 or so) rows, some of checkboxes were
>     omitted, and not all selected messages were distributed/rejected.
>
I didn't know. I will test and think of a solution if I see a problem. 
Was it reproducible ?

**Comment by ikedas** [comment] 2017-12-18 04:11
@l4uc3,
> I was careful not to put a form inside a form. Could you point me inside
the code where you see a nested element ?

I misunderstood. Indeed `<form>` are not nested.

But I still concerned: `form` attribute of `<fieldset>` element is widely supported? (several contemporary UAs [support it](https://caniuse.com/#feat=form-attribute), but some UAs not fully HTML5-compliant may not).

> > * On 6.1.x, it was sometimes reported that, with a form including a
> >     table having many (20, 30 or so) rows, some of checkboxes were
> >     omitted, and not all selected messages were distributed/rejected.
> 
> I didn't know. I will test and think of a solution if I see a problem.
> Was it reproducible ?

I personally could not reproduce, but more than one persons complained it.

**Comment by ikedas** [comment] 2017-12-25 09:44
PR above seems to be able to avoid problem I pointed out:
  - Use of `<table>` in `<form>`.
  - Separate `<fieldset>` compliant to HTML5.

**Comment by l4uc3** [comment] 2018-01-03 21:07
@ikedas : thanks for your help. I put the new files on our servers.

**Comment by ikedas** [comment] 2018-01-04 04:01
Thanks for checking my addition. If no problem is found in a few days, merge commits and close this issue.

**Comment by ikedas** [comment] 2018-01-06 23:33
Merged. Thanks again l4uc3.

**Closed by ikedas** 2018-01-06 23:33 UTC
Labels: enhancement
