### ISSUE TITLE
Force Spool digest

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1280] opened 2021-11-23 15:04 UTC
Hello,
I'm using Sympa 6.2.40.
I have mails into /var/spool/sympa/digest/name_liste.
How can i force sending these mails ? Or to deplace them into postfix queue ?
Yours Faithfully

**Comment by ikedas** [comment] 2021-11-24 01:10
Hi @khaoula-abaidi ,

You may use `sympa.pl --send_digest`.  Please read the [manual page of `sympa.pl`](https://sympa-community.github.io/gpldoc/man/sympa.1.html).

**Comment by khaoula-abaidi** [comment] 2021-11-24 08:49
Thank you for your response. 
Into the manual this option is used to force send_digest for all lists into /var/spool/sympa/digest ? 
Is it possible to use it only for  a specific list ?

**Comment by ikedas** [comment] 2021-11-28 03:08
No, this option is used to force sending digest for all of lists.

**Comment by ikedas** [comment] 2022-04-22 02:05
Duplicate of #1097 .

**Closed by ikedas** 2022-04-22 02:05 UTC
Labels: question
