### ISSUE TITLE
Editing Moderators Requires Restart to Take Effect

### ISSUE THREAD

**Issue by miralgj** [sympa-community/sympa#7] opened 2017-04-12 12:39 UTC
Version: 6.2.14
OS: RHEL 7

When adding, or editing, a list's moderator list in a newsletter list, newly added moderators are rejected by Sympa as not having permission to send to the list until the Sympa software is restarted. 

From what I can tell, when the list config changes it's supposed to trigger a cache update in the database but I don't believe this is ocurring.

**Comment by racke** [comment] 2017-04-12 12:49
IMHO, caching of list owners and moderators is **severely flawed** in 6.2. Ran into the same problem a while ago and I finally resorted to just disable this sort of caching by a hack in the code.

Thanks for the report.

**Comment by miralgj** [comment] 2017-04-12 12:50
@racke Can you share the hack that you did? I'd love to work around it the same way if possible.

**Comment by racke** [comment] 2017-04-12 13:04
Let me stress that it is a *hack* and may cause problems. Certainly not a proper fix.

Method get_admins in src/lib/Sympa/List.pm:

```
     # Fill caches.
     $self->{_admin_cache} ||= {};
+    delete $self->{_admin_cache}{$role} if exists $self->{_admin_cache}{$role};
+
```

I also patched wwsympa.cgi, because changes to moderators etc. didn't end up in the database:

```
diff --git a/cgi-bin/wwsympa.fcgi b/cgi-bin/wwsympa.fcgi
index b976a1f..0e28f00 100755
--- a/cgi-bin/wwsympa.fcgi
+++ b/cgi-bin/wwsympa.fcgi
@@ -12431,7 +12431,7 @@ sub do_edit_list {
     }

     ## Reload config to clean some empty entries in $list->{'admin'}
-    $list = Sympa::List->new($list->{'name'}, $robot, {'reload_config' => 1});
+    $list = Sympa::List->new($list->{'name'}, $robot, {'reload_config' => 1,'force_sync_admin' => 1});

     unless (defined $list) {
         Sympa::Report::reject_report_web('intern', 'list_reload', {},
```

**Comment by miralgj** [comment] 2017-04-12 13:18
@racke Thank you very much!

**Comment by ikedas** [comment] 2017-04-14 01:21
@racke May we apply your hack?

**Comment by racke** [comment] 2017-04-15 07:25
On 04/14/2017 03:21 AM, IKEDA Soji wrote:
> @racke <https://github.com/racke> May we apply your hack?
> 

Not really. It deserves another look, as of now it just prevents the caching of the information.

Regards
        Racke

-- 
Ecommerce and Linux consulting + Perl and web application programming.
Debian and Sympa administration.

**Comment by racke** [comment] 2017-04-22 06:27
@ikedas: actually the patch to wwsympa should be fine and we could apply that one.

**Comment by ikedas** [comment] 2017-04-23 15:30
@racke, thanks for investigating.  I have no objection to apply it.

**Comment by moschlar** [comment] 2017-06-01 08:01
I think it would be good to also add `force_sync_admin` in `bin/sympa.pl` in the block for `reload_list_config`...
At least, that fixed it for me.

**Comment by racke** [comment] 2017-06-01 14:19
Thanks for the suggestion, I added this through ec77aaaff.
@moschlar, @ikedas could you check whether I got it correct?

**Comment by moschlar** [comment] 2017-06-01 17:33
I think so - but I'm really not an expert at all. I know neither Perl nor Sympa that well. ;-)

**Comment by ikedas** [comment] 2017-06-11 07:33
Are there any more fixes on this issue? If not, I'd like to close.

**Comment by racke** [comment] 2017-06-11 08:35
@ikedas Go ahead, we can open new issues if this or a similar problem pops up again with 6.2.17 release.

**Comment by ikedas** [comment] 2017-06-11 09:20
Okey, closed. Thanks for reporting and fixing bugs!

**Comment by MargoM** [comment] 2017-08-26 22:06
Still facing with this problem.

While refreshing wws/lists page, sometimes shows list@domain (Owner) and sometimes without owner. After restarting spawn-fcgi service, everything works fine. 

Sympa version: Sympa 6.2.19b.1
OS: CentOS Linux release 7.3.1611

**Comment by MargoM** [comment] 2017-09-10 11:57
@ikedas 

Why change in List.pm is not applied to code? Is it hack or?
I mean this change in List.pm that racke commented: https://github.com/sympa-community/sympa/issues/7#issuecomment-293568974. I have to change it manually, otherwise it's not working properly.

**Comment by ikedas** [comment] 2017-09-14 04:01
@MargoM, the change you suggested is the same as stopping use of `{_admin_cache}`.

In fact `{_admin_cache}` is the root of evil, however, we should consider how the change will affect performance.  Could you check a minor change below?

**Comment by MargoM** [comment] 2017-09-14 08:08
@ikedas, unfortunately, this minor change didn't helped me.

**Comment by ikedas** [comment] 2017-09-14 09:58
@MargoM, owners sometimes shown or not shown is included from data source, or owners set in list config page?
- In former case, delay of update may be controled by `ttl` (Inclusions timeout), 3600s by default.
- In latter case, delay may be usually at least a few seconds.

This is the feature at this moment. I guess radical fix will be done in the future.

**Comment by MargoM** [comment] 2017-09-14 11:04
@ikedas, while logging in as "normal owner" sometimes I can change list configuration and sometimes shows red textbox "AUTHORIZATION REJECT (edit_list_request) This action is restricted to list owners. ".
While logging in as "listmaster", in list configuration page, in textfields owner values are stable, but in left menu ("List Options") where the Owners are described this line is changing almost everytime I refresh the page.

**Comment by racke** [comment] 2017-10-12 13:40
At this point I would suggest to add a global/list option to switch off the admin cache, which probably should to on by default.

**Comment by MargoM** [comment] 2017-10-12 20:47
@racke how I can switch off the admin cache? You mean this: src/lib/Sympa/List.pm, https://github.com/sympa-community/sympa/issues/7#issuecomment-293568974? I'm using this change in List.pm and it seems to be working fine.

**Comment by ikedas** [comment] 2017-10-23 01:39
The PR above can solve the problem.  Please check it (it will be included in next beta, 6.2.23b.1).

**Comment by ikedas** [comment] 2017-12-06 09:09
If problem will not be reported reproducing with 6.2.23b.2 by 14 Dec., I'll close this issue.

**Comment by tannevaled** [comment] 2017-12-12 15:33
[root@listes ~]# yum info sympa
Modules complémentaires chargés : security
Paquets installés
Nom        : sympa
Architecture        : x86_64
Version     : 6.2.23b.2
Révision     : 1.20171130.RHEL6
Taille        : 18 M
Dépôt         : installed
Depuis le dépôt   : sympa-ja.org
Résumé        : Gestionnaire de listes électroniques
URL         : http://www.sympa.org
Licence       : GPLv2+
Description : 

same error here ->  ERREUR INTERNE (edit_list) - Impossible de synchroniser les administrateurs de la liste

**Comment by ikedas** [comment] 2017-12-13 04:17
@tannevaled, could you please show the Sympa log?

**Comment by tannevaled** [comment] 2017-12-14 11:41
[sympa_log.txt](https://github.com/sympa-community/sympa/files/1559022/sympa_log.txt)

**Comment by tannevaled** [comment] 2017-12-14 11:43
L'utilisateur lismaster@domain.tld a été confronté à une erreur
interne
(Interface web - ACTION : Command process - LIST :
xdev@listes.domain.tld) :

Problème de synchronisation des administrateurs de la liste 'xdev'

Consultez les logs pour plus de détails.

**Comment by ikedas** [comment] 2017-12-15 04:16
@tannevaled,
```
Dec 14 12:12:13 listes wwsympa[12358]: err main::#1606 > main::do_edit_list#10559 > Sympa::List::new#399 > Sympa::List::sync_include_admin#7165 > Sympa::List::add_list_admin#3978 > Sympa::DatabaseDriver::PostgreSQL::do_prepared_query#98 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO admin_table (user_admin, comment_admin, list_admin, robot_admin, date_admin, update_admin, reception_admin, visibility_admin, subscribed_admin, included_admin, include_sources_admin, role_admin, info_admin, profile_admin) VALUES (?, ?, ?, ?, 'epoch'::timestamp with time zone + '1513249933 sec', 'epoch'::timestamp with time zone + '1513249933 sec', ?, ?, ?, ?, ?, ?, ?, ?)": (23505) ERROR:  duplicate key value violates unique constraint "ind_admin"
Dec 14 12:12:13 listes wwsympa[12358]: err main::#1606 > main::do_edit_list#10559 > Sympa::List::new#399 > Sympa::List::sync_include_admin#7165 > Sympa::List::add_list_admin#4009 Unable to add admin listmaster@domain.tld to table admin_table for list Sympa::List <xdev@listes.domain.tld>:
Dec 14 12:12:13 listes wwsympa[12358]: err main::#1606 > main::do_edit_list#10559 > Sympa::List::new#399 > Sympa::List::sync_include_admin#7167 Failed to add new owner(s) to list Sympa::List <xdev@listes.domain.tld>
Dec 14 12:12:13 listes wwsympa[12358]: err main::#1606 > main::do_edit_list#10559 > Sympa::List::new#399
```
The error ``duplicate key value violates unique constraint "ind_admin"`` is what issue #11 deals with. Please continue there. Merci.

**Comment by ikedas** [comment] 2017-12-15 04:19
Problem has no longer been reported. Issue is closed.

**Closed by ikedas** 2017-12-15 04:19 UTC
Labels: bug
