### ISSUE TITLE
Problem with moderating subscriptions in 6.2.44

### ISSUE THREAD

**Issue by skunktoy** [sympa-community/sympa#708] opened 2019-07-23 19:38 UTC
So on line 81 of sympa/default/web_tt2/sigindex.tt2
in sympa 6.2.44 there is :
type="submit" form="submindex" name="action_decl_add"
it should be :
type="submit" form="subindex" name="action_decl_add"

**Comment by ldidry** [comment] 2019-07-24 06:45
@skunktoy is it `sigindex.tt2`? I can’t find `submindex` in [it](https://github.com/sympa-community/sympa/blob/6.2.44/default/web_tt2/sigindex.tt2). I already fixed that typo in `subindex.tt2` though: https://github.com/sympa-community/sympa/pull/674

I think this issue is a duplicate of #673.

**Closed** 2019-07-24 06:53 UTC
Labels: bug, duplicate

**Comment by skunktoy** [comment] 2019-07-24 13:46
subindex.tt2 

Sent from my reverse Polish 
iPhone
