### ISSUE TITLE
accessing db_additional_subscriber_fields fields in footer vs. tt2 templates

### ISSUE THREAD

**Issue by igoltz** [sympa-community/sympa#1494] opened 2022-10-11 09:22 UTC
Accessing db_additional_subscriber_fields fields in footer works but fails within  tt2 templates

Version
-------
6.2.68

Installation method
-------------------
from source

Expected behavior
-----------------
user.optout_uuid should be parsed and populated with data in footer and tt2 template files (e.g. welcome.tt2)

Actual behavior
---------------
user.optout_uuid returns nothing in tt2 template files

Steps to reproduce
------------------
1. modify sympa database
```
alter table subscriber_table add column optout_uuid varchar(64) default(uuid());
```

2. add optout_uuid to db_additional_subscriber_fields parameter in 
```
/etc/sympa/sympa.conf

...
db_additional_subscriber_fields optout_uuid
...
```

3. use new subscriber field in footer
3.1 create/modify footer and enable it in list
```
/var/lib/sympa/list_data/robot/list/message_footer

...
[% wwsympa_url %][% 'auto_signoff' | url_abs([listname], {email => user.email, uuid =>user.optout_uuid}) %]
...
```

3.2 send mailing
Result: URL is created and uuid param is correctly filled (&uuid=123456xyz)

4. use new subscriber field in welcome message
4.1 modify welcome.tt2 for the list
```
/var/lib/sympa/list_data/robot/list/mail_tt2/welcome.tt2

...
[% wwsympa_url %][% 'auto_signoff' | url_abs([listname], {email => user.email, uuid =>user.optout_uuid}) %]
...
```

4.2 subscribe to list
Result: URL is created but uuid param is empty (&uuid=)

**Comment by ikedas** [comment] 2022-10-11 09:44
Just for clarification: When is the `optout_uuid` field in the `subscriber_table` set the value in each case?
In the case of footer, the subscriber has already had the row in the table and the field may be filled in advance.
But in the case of welcome message, it seems to me that the field cannot be filled, since the subscriber has not had the row in the table and the message is sent as soon as it is added.

**Comment by igoltz** [comment] 2022-10-11 12:00
That would mean the subscriber is not persisted to the database yet but the welcome message already sent out, right?
Yes this would explain the behaviour. 
How to find out what exactly it the process during subscriber creation and how could the field populated before sending the welcome messag?

**Comment by igoltz** [comment] 2022-10-11 13:22
In this case the row already exists in database, the column has a default which is used on insert. Thus the field should be populated when sending the welcome message, correct?
Probably we now have to check whats happening in $list->send_probe_to_user('welcome', $email)

**Comment by igoltz** [comment] 2022-10-12 07:17
The database is MariaDB 10.5
Subscribers get the column filled on inserting, the value is shown in the GUI.
Maybe the user object in Sympa is not refreshed from database in the subscribe process?

**Comment by ikedas** [comment] 2022-10-12 09:01
@igoltz , I could reproduce it.

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1495.patch) and check if the problem solved?

And note: Subscriber's information is included in `subscriber` template variable.  Use `subscriber.optout_uuid` instead of `user.optout_uuid`.

**Comment by igoltz** [comment] 2022-10-12 12:48
@ikedas , thank you very much. I patch and test asap!
Documentation about Sympa templates is [here](https://www.sympa.community/manual/customize/basics-templates.html) but probably we missed other pages. Could you please point us to them.
And whats the difference between user and subscriber? I think user is the global entry with address and maybe password, subscriber the list specific entry.

**Comment by ikedas** [comment] 2022-10-12 13:20
The variable `subscriber` is undocumented.  However it was available before the code had been broken (See [here](https://github.com/sympa-community/historic-sympa/blob/af7ed77/src/lib/Sympa/List.pm#L2485) in 6.2alpha).

I don't know why footer and template give different set of variables (it looks simply due to a lack of consideration).  Such inconsistencies should be fixed in the future, but for now we'd be better just to fix the code that has not been working.

**Comment by igoltz** [comment] 2022-10-13 13:03
@ikedas 
I confirm that the patch works. But one must use subscriber.optout_uuid in tt2.
May the documentation get an update about this too please. Thank you!

**Closed** 2022-11-16 00:34 UTC
Labels: bug, on going

**Comment by ikedas** [comment] 2022-11-16 00:36
The fix was merged.  @igoltz , thank you for reporting bug!

A separate issue will be submitted for inconsistencies in the feature.
