### ISSUE TITLE
inclusion_table not updated when deleting all list inclusions sources

### ISSUE THREAD

**Issue by cgx** [sympa-community/sympa#745] opened 2019-09-06 17:39 UTC
Version
-------
6.2.32

Installation method
-------------------
RPM from sympa-ja.org

Expected behavior
-----------------
When deleting all the list inclusions from a list, the relevant entries from the database table *inclusion_table* should be deleted.

Actual behavior
---------------
When deleting all the list inclusions from a list (`include_sympa_list`), the relevant entries from the database table *inclusion_table* are not deleted. However, if there are at least two list inclusions and I delete only one of them, the database table is properly updated.

Additional information
----------------------
Main side effect of this bug:

 1. List A includes the members of list B;
 2. The inclusion of list B is removed. It no longer appears on the edit page of list A.
 3. On the admin page of list B, it's still impossible to close the list because Sympa reports that list B is still included in list A.

**Comment by ikedas** [comment] 2019-09-07 05:53
Currently I can't check if the bug will be reproduced with 6.2.32.  However, such misbehavior seems to be fixed by #693.

@cgx, if possible, please check current beta, 6.2.45b.3.

**Comment by ikedas** [comment] 2019-09-27 04:19
Closed for now.

**Comment by xavierba** [comment] 2020-01-07 09:32
I may be hitting this on 6.2.48.
@cgx, any chance to try a more recent version than 6.2.32 ? EPEL does have latest 6.2.48 in stable and 6.2.52 in testing.

**Comment by xavierba** [comment] 2020-03-13 17:19
@cgx did you check again with a more up to date version ? Current is 6.2.54, available from EPEL testing, while previous 6.2.52 is in EPEL stable.
I'll try and reproduce what I was seeing next week.

**Comment by xavierba** [comment] 2020-03-16 12:57
Runnning sympa 6.2.54 from EPEL 6.
I have a list with no datasource defined in the conf (/var/lib/sympa/list_data/some_list/config).
No datasource definition is shown from the WUI.
A dump of the lists members shows some mail from a list that was previously included.
Lists members cannot be sync'ed from the WUI, no button.
Sync'ing the members list from the command line doesn't remove them.
That previous included list was still opened. Closing the list doesn't change anything to the above behavior. I had no issue closing the list, which would have been the case if it was still included in another list.

I'm not sure how to force a sync, nor how to check the database for the lists subscribers.

**Comment by ikedas** [comment] 2020-03-16 14:23
Maybe duplicate of #858 .

**Comment by xavierba** [comment] 2020-03-16 14:53
I will try to patch #905 on top of 6.2.54 and test for any improvement.

**Comment by cgx** [comment] 2020-12-07 21:12
I cannot reproduce this issue with release 6.2.58. Thanks!

**Comment by ikedas** [comment] 2020-12-08 01:23
@cgx & @xavierba , thanks for confirming.  Close.

**Comment by salaun-urennes1** [comment] 2021-09-02 11:44
I have the same issue of mailing lists I can't close because the were included by a list that has been removed in the meanwhile. 

I noticed that the bug has been fixed, but does Sympa provide a way the do the cleanup of the database tables?

**Comment by ikedas** [comment] 2021-09-03 01:55
As you wrote, they will be removed by `sync_include` task which is executed after removal of inclusion setting.  Because Sympa cannot decide which members may be removed until it is sure that there are no more new members that can be included.

Such a delay can occur even if the inclusion settings have not been removed. Especially, if `nosync_time_ranges` is set, the deletion of a member that is no longer included can be postponed for up to 24 hours (cf. ae01bc3 in PR #516).

**Comment by salaun-urennes1** [comment] 2021-09-03 07:30
I realize I need to be more precise.
Wa are running Sympa 6.2.48.
On our Sympa server I found many entries in the `inclusion_table` that looked like this :
```
role_inclusion | source_inclusion | target_inclusion
-------------------------------------------------------------------
member          | list_a@my.robot       | list_b@my.robot
```

`list_b` is a list that has been closed and purged many months/years ago.
`list_a` is a list I wish to close, but when I try to I get an error and the log say: 
`err main::#1033 > Sympa::Family::close_family#508 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::close_list::_twist#57 List Sympa::List <list_a@my.robot> is included by other list: cannot close it`

I can't rely on the `sync_include` task to perform the cleanup in the `inclusion_table` because `sync_include` task is not a global task, it is related to a list and since `list_b` has disappeared, no way to have a `sync_include` task run for this list.

**Comment by ikedas** [comment] 2021-09-03 09:22
The problem seems solved on later version (6.2.56).  Please see the comments above and related issues / PRs.

**Comment by ikedas** [comment] 2021-09-03 09:29
I was confused a bit.

In any case, @salaun-urennes1 , please submit a new issue. In addition, it would be helpful if you could confirm whether the recent version has problem or not before reporting the problem.

This issue is closed.

**Closed by ikedas** 2021-09-03 09:29 UTC
Labels: bug, duplicate

**Comment by salaun-urennes1** [comment] 2021-09-06 07:21
I will have a try with the latest Sympa release, as soon as I have some spare time.
