### ISSUE TITLE
sympa include doesn't work if the users were deleted before

### ISSUE THREAD

**Issue by colttt** [sympa-community/sympa#1888] opened 2024-09-03 15:04 UTC
Version
-------
Sympa 6.2.70

Installation method
-------------------
via package on Debian 12

Expected behavior
-----------------
sympa include <listname> should always import the users

Actual behavior
---------------
sympa include <listname> don't add users when they are deleted before

Steps to reproduce
------------------

* create a list where the subscribers/users come from a textfile
* import it and add a subscriber/user manually
* you should now see all this subscribers/users
* now delete all subscribers: under Users, mark them all and click on delete mail addresses
* now try to include them again via command line `sympa include <listname>` or via click in the web gui 
* it doesn't work no one is included, no error messages or something like that (just _include [notice] Inclusion succeeded (0 added, 0 deleted, 0 updated)._ ), also `sympa debug include <listname>` doesn't work (it also says that  _Invalid argument 'debug' (command is expected)_ )

Additional information
----------------------

**Comment by ikedas** [comment] 2024-09-03 21:01
Duplicate of #1694.

Check the exclusion table of the list.

**Closed by ikedas** 2024-09-03 21:01 UTC
Labels: bug
