### ISSUE TITLE
Email causes Sympa service to crash indefinitely. Sympa service cannot be started anymore

### ISSUE THREAD

**Issue by jengels** [sympa-community/sympa#1557] opened 2022-12-20 14:52 UTC
Version
-------
Sympa version 6.2.68 running on CentOS 7.

lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

Installation method
-------------------
Using standard RPM's from EPEL repository:
sympa-6.2.68-1.el7.x86_64
sympa-httpd-6.2.68-1.el7.x86_64

Expected behavior
-----------------
Sympa should move problematic email to "/var/spool/sympa/msg/bad" and keep on delivering emails.

Actual behavior
---------------
Sympa service dies completely and cannot be started anymore until the problematic email is manually removed from "/var/spool/sympa/msg".

Steps to reproduce
------------------
sending the following email through a Sympa mailing list.

URL to raw email (this URL expires on 31.01.2023!) :
https://desycloud.desy.de/index.php/s/KnR7aAan9yrSDe3

The URL is password protected since it contains sensitive data, please let me know how I can hand you over the password.

Additional information
----------------------

Please find below the anonymized log data. Please let me know if you need any more details.

Dec 16 11:07:18 my-hostname sympa_msg[3839]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <my-list@domain.tld.1671183281.41602>; envelope_sender=sender-address@domain.tld; message_id=7BDBD904-B22F-4DC8-93E4-A8648A8C002C@domain.tld; sender=sender-address@domain.tld 
Dec 16 11:07:18 my-hostname sympa_msg[3839]: info Sympa::Message::check_smime_signature() Sympa::Message <my-list@domain.tld.1671183281.41602>: Unable to verify S/MIME signature: Crypt::SMIME#check: failed to check the signature: error:0D0D40D2:asn1 encoding routines:SMIME_read_ASN1:no multipart body failure at /usr/share/sympa/lib/Sympa/Message.pm line 1319. 
Dec 16 11:07:18 my-hostname sympa_msg[3839]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <my-list@domain.tld.1671183281.41602> for Sympa::List <my-list@domain.tld> with priority 5, <7BDBD904-B22F-4DC8-93E4-A8648A8C002C@domain.tld> 
Dec 16 11:07:18 my-hostname sympa_msg[3839]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::DoMessage::_twist#93 > Sympa::Spindle::DoMessage::_check_command#159 > Sympa::Message::get_plain_body#2497 > Sympa::Message::_as_singlepart#2566 > MIME::Entity::make_singlepart#1184 DIED: Can't call method "head" on an undefined value at /usr/share/perl5/vendor_perl/MIME/Entity.pm line 1184.

**Comment by ikedas** [comment] 2022-12-21 00:48
Duplicate of #1454.  This bug has been fixed on 6.2.70.

**Closed by ikedas** 2022-12-21 00:48 UTC
Labels: bug
