### ISSUE TITLE
Qmail Configuration

### ISSUE THREAD

**Issue by acastelletto** [sympa-community/sympa#977] opened 2020-08-02 07:06 UTC
Hi Sympa team. I'm struggling on a couple of levels with installing and configuring sympa.
The first thing I'm struggling with is the mail server configuration. Our host provider uses Qmail as the outgoing mail agent. Is there a configuration guide for Qmail available. I think I have most of it in that I have created aliases in the Qmail configuration. However, I'm wondering just what I should put into the sympa configuration file.
The default configuration looks something like:
endmail_aliases    /etc/mail/aliases          
aliases_program     newaliases
aliases_db_type     hash
sendmail               /usr/lib/sendmail
#sendmail_args       (if you use sendmail(1), this need not change)

The path to the mail program seems pretty obvious. It's the path to the binary. But, the aliases file stumps. Qmail uses a directory with separate .qmail files for each alias. 

I'm also having some trouble with a firewall. Are there any ports other than the usual mail port or http port that I should have our service provider open up?

Thanks in advance for any help.

**Comment by ikedas** [comment] 2020-09-01 01:55
Duplicate of #982 .

**Closed by ikedas** 2020-09-01 01:55 UTC
Labels: help wanted, question
