### ISSUE TITLE
Web Interface sympa 6.2.66

### ISSUE THREAD

**Issue by abkayla** [sympa-community/sympa#1422] opened 2022-06-15 15:54 UTC
Problem:  Web interface not found

Version : Sympa: 6.2.66 

Installation method:

I had my server with Ubuntu 20.04 LTS with sympa 6.2.40 version
I had upgrade the Os server into Ubuntu 22.04 LTS (command line) 
Then my Sympa version is upgraded into 6.2.66
My synchronization list behavior seems with no problem using the command line and the sympa program sympa.pl
But the web interface is inaccessible. 
My web server is Apache Apache/2.4.52
Expected behavior: I have to get the home page interface web for my lists
Actual behavior: I have 404 not found . The requested URL was not found on this server.
Tell us what happens instead of the expected behavior : 
I used the manual for the upgrade notes  (https://sympa-community.github.io/manual/upgrade/notes.html ) but i have the same error.
My robot.conf  content is : 
``` code
wwsympa_url     http://devlistes.my-domain.fr/sympa
title       Test list my-domain 
```
My sympa.conf content is : 
``` code
wwsympa_url     http://6tm-test.my-domain.fr/wws
```
The http_host into sympa.conf is the left as the default value.

Thank you for your help,
Yours Faithfully

**Comment by khaoula-abaidi** [comment] 2022-06-15 16:41
Into my Virtual host configuration : 
 ScriptAlias /sympa /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi

When i run my wwsympa-wrapper.fcgi , i have this error Status: 421 Misdirected Request

**Comment by ikedas** [comment] 2022-06-15 20:12
@khaoula-abaidi , could you please show the current configuration of Apache?

**Comment by khaoula-abaidi** [comment] 2022-06-16 07:48
Hello, 
Here is my Apache configuration : 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<IfModule mod_ssl.c>
<VirtualHost ipaddress:443 >
    ServerName devlistes.my-domain.fr:443
    RedirectMatch ^/$ /sympa/

<IfModule mod_fcgid.c>
        Alias /static-sympa /usr/share/sympa/static_content
        <Directory /usr/share/sympa/static_content>
            Require all granted
        </Directory>
        Alias /css-sympa /var/lib/sympa/css
        <Directory /var/lib/sympa/css>
        Require all granted
        </Directory>
        Alias /pictures-sympa /var/lib/sympa/pictures
        <Directory /var/lib/sympa/pictures>
        Require all granted
        </Directory>
        ScriptAlias /sympa /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi
        ScriptAlias /sympa2 /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi
        <Directory /usr/lib/cgi-bin/sympa>
            Require all granted
        </Directory>
</IfModule>

SSLEngine on
SSLCertificateFile /etc/ssl/vm-name/vm-name.crt
SSLCertificateKeyFile /etc/ssl/private/vm-name_fr.key
SSLCACertificateFile /etc/ssl/vm-name/Chain_Intermediate_Root_Sectigo.crt
ErrorLog ${APACHE_LOG_DIR}/devlistes.error.log
CustomLog ${APACHE_LOG_DIR}/devlistes.access.log combined
</VirtualHost>
<IfModule mod_ssl.c>
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
And that are the permissions for wwsympa.fgci 
-rwxr-xr-x 1 root  root  599996 déc.  11  2021 wwsympa.fcgi
-rwsr-xr-x 1 sympa sympa 599996 juin  15 19:20 wwsympa-wrapper.fcgi

**Comment by ikedas** [comment] 2022-06-16 08:52
It looks to me that this is not the problem of Sympa.  Please try:

  * Reload the page (clear cache of the browser).
  * In case that you use wildcard certificate, consider not using it (if you or your organization can do).
  * Check the questions & answers on the net, such as [StackOverflow](https://stackoverflow.com/search?q=apache+421+Misdirected+Request).

---
Besides, it would be helpful if you could show the configuration file in text. If someone try to reproduce the problem, they have to type everything .

**Comment by whbogado** [comment] 2022-09-16 20:51
I had exactly the same situation.
I solved it by enabling mod_proxy_fcgi, which was disabled for some reason and prevented Apache from loading de directives in conf-enabled/sympa.conf.

`# a2enmod proxy_fcgi`
`# systemctl restart apache2`

After that the Web interface resumed normal operations.

**Comment by khaoula-abaidi** [comment] 2022-11-03 13:19
> I had exactly the same situation. I solved it by enabling mod_proxy_fcgi, which was disabled for some reason and prevented Apache from loading de directives in conf-enabled/sympa.conf.
> 
> `# a2enmod proxy_fcgi` `# systemctl restart apache2`
> 
> After that the Web interface resumed normal operations.

Thank you for your proposition.
Now i can access to sympa web interface. 
But i have this error, 
 ```
wwsympa[13530]: err main::#1073 [robot ] [client 172.30.125.44] Config error: WWSympa should run with UID 117 (instead of 0). *** Switching to maintenance mode. ***
err main::#1073 [robot ] [client 172.30.125.44] Config error: WWSympa should run with UID 117 (instead of 0). *** Switching to maintenance mode. ***

I had check the sympa user and group and its : 
`uid=117(sympa) gid=125(sympa) groups=125(sympa)`


Thank you very much again for your help


```

**Comment by ikedas** [comment] 2022-11-04 05:38
@khaoula-abaidi , could you please show these things?
  - Current configuration of Apache.
  - The owner and mode of `wwsympa-wrapper..fcgi` (the result of `ls -l`).

**Comment by khaoula-abaidi** [comment] 2022-11-04 07:46
Hello @ikedas , 
> @khaoula-abaidi , could you please show these things?
> 
>     * Current configuration of Apache.
> 
`<IfModule mod_ssl.c>
<VirtualHost myrobot.domain:443 >
    ServerName myrobot.domain:443
    RedirectMatch ^/$ /sympa/

<IfModule mod_fcgid.c>
        Alias /static-sympa /usr/share/sympa/static_content
        <Directory /usr/share/sympa/static_content>
            Require all granted
        </Directory>
        Alias /css-sympa /var/lib/sympa/css
        <Directory /var/lib/sympa/css>
        Require all granted
        </Directory>
        Alias /pictures-sympa /var/lib/sympa/pictures
        <Directory /var/lib/sympa/pictures>
        Require all granted
        </Directory>
        ScriptAlias /sympa /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi
        ScriptAlias /sympa2 /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi
        <Directory /usr/lib/cgi-bin/sympa>
            Require all granted
        </Directory>
</IfModule>

SSLEngine on
SSLCertificateFile /etc/ssl/vl-sympa_domain/vl-sympa_domain.crt
SSLCertificateKeyFile /etc/ssl/private/vl-sympa_domain.key
SSLCACertificateFile /etc/ssl/vl-sympa_domain/Chain_Intermediate_Root_Sectigo.crt
ErrorLog ${APACHE_LOG_DIR}/myrobot.error.log
CustomLog ${APACHE_LOG_DIR}/myrobot.access.log combined
</VirtualHost>
<IfModule mod_ssl.c>`
>     * The owner and mode of `wwsympa-wrapper.fcgi` (the result of `ls -l`).

`-rwsr-sr-x 1 sympa sympa 14488 févr. 25  2020 /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi`

**Comment by ikedas** [comment] 2022-11-05 00:51
Please check if these are on the same host: The error log, current configuration of Apache, and the owner/mode of wwsympa-wrapper.fcgi.

**Comment by khaoula-abaidi** [comment] 2022-11-05 07:08
> Please check if these are on the same host: The error log, current configuration of Apache, and the owner/mode of wwsympa-wrapper.fcgi.

All files: error log, configuration of Apache wwsympa-wrapper.fcgi  are on the same host

**Comment by ikedas** [comment] 2022-11-05 09:31
Can you reboot that host?

**Comment by khaoula-abaidi** [comment] 2022-11-05 16:46
> Can you reboot that host?

Yes, I will do it then I put my feedback

**Comment by khaoula-abaidi** [comment] 2022-11-07 08:54
After rebooting the host, 
I have 500 Internal Server Error

**Comment by khaoula-abaidi** [comment] 2022-11-07 14:14
Hello @ikedas ,
After many tests ,
I had change the permissions to 771 for the subdirectories:
/var/spool/bulk
/var/spool/moderation
/var/spool/outgoing
/var/spool/subscribe
/var/spool/viewmail

Then into the program : /usr/lib/cgi-bin/sympa/wwsympa.fcgi from 
$robot = $ENV{SYMPA_DOMAIN};  
to
$robot = "devlistes.my-domain.fr";

Then i executed the programs : 
upgrade_bulk_spool.pl and upgrade_send_spool.pl 

Then i restarted sympa and apache services.

=> The interface web is accessible.

But , i have an error and i'n not able to navigate into the web interface ( login, search a list, etc) :+1: 

`Erreurs : bug in logic. Ask developer at /usr/share/sympa/lib/Sympa/Scenario.pm line 149. `

`DIED: bug in logic. Ask developer at /usr/share/sympa/lib/Sympa/Scenario.pm line 149.
 at /usr/share/sympa/lib/Sympa/Scenario.pm line 149.
	Sympa::Scenario::new('Sympa::Scenario', 'devlistes.my-domain.fr', 'topics_visibility', 'name', undef) called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 15760
	main::export_topics('devlistes.my-domain.fr') called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 2744
	main::check_param_in() called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 1514
`

**Comment by ikedas** [comment] 2022-11-07 23:12
> Hello @ikedas ,
> After many tests ,
> I had change the permissions to 771 for the subdirectories:
> /var/spool/bulk
> /var/spool/moderation
> /var/spool/outgoing
> /var/spool/subscribe
> /var/spool/viewmail

I suppose this change corrected 500 error.

> Then into the program : /usr/lib/cgi-bin/sympa/wwsympa.fcgi from
> $robot = $ENV{SYMPA_DOMAIN};
> to
> $robot = "devlistes.my-domain.fr";

This change is not a normal operation.  Instead you should do either:
  - Set `domain` parameter in `sympa.conf` to `devlistes.my-domain.fr` (also it should contain `wwsympa_url` parameter with appropriate value).
  - Create `$SYSCONFDIR/devlistes.my-domain.fr/robot.conf` file (It should contain at least `wwsympa_url` parameter).

Doing either of above, mail domain and `wwsympa_url` will be assosiated correctly.

> Then i executed the programs : upgrade_bulk_spool.pl and upgrade_send_spool.pl
> 
> Then i restarted sympa and apache services.
> 
> **Result:**
> 
> => The interface web is accessible.
> 
> **Error**
> 
> But , i have an error and i'n not able to navigate into the web interface ( login, search a list, etc) 👍
> 
> `Erreurs : bug in logic. Ask developer at /usr/share/sympa/lib/Sympa/Scenario.pm line 149. `
> 
> `DIED: bug in logic. Ask developer at /usr/share/sympa/lib/Sympa/Scenario.pm line 149. at /usr/share/sympa/lib/Sympa/Scenario.pm line 149. Sympa::Scenario::new('Sympa::Scenario', 'devlistes.my-domain.fr', 'topics_visibility', 'name', undef) called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 15760 main::export_topics('devlistes.my-domain.fr') called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 2744 main::check_param_in() called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 1514 `

You may hit this bug: #1242.
Remove customized `topics.conf` at once, then create it again.

**Comment by khaoula-abaidi** [comment] 2022-11-08 19:03
> 

@ikedas ,
Thank you, the configurations asked from you let me access to the interface web without problems.
I confirm that the customized topics.conf where the reason for the error.

A last question before closing the issue, Would you confirm to me that there is no changes for authentification using LDAP between 6.2.40 version and 6.2.66 ? 

Thank you again

**Comment by khaoula-abaidi** [comment] 2022-11-09 07:38
> Hi @khaoula-abaidi ,
> 
> > A last question before closing the issue, Would you confirm to me that there is no changes for CAS authentification between 6.2.40 version and 6.2.66 ?
> 
> As far as I know, there are no changes on CAS between these versions.

Hi @ikedas ,
ok, i have a problem with the CAS authentification into the interface web ( i can't be authenticated with this method).
I will check  the note releases to resolv this problem. 
Thank again for all to your help

**Comment by ikedas** [comment] 2023-01-07 12:52
The initial problem appears to have been resolved; please ask separately about CAS.  Close.

**Closed by ikedas** 2023-01-07 12:52 UTC
Labels: question
