### ISSUE TITLE
/sympa/reject/ URLS no longer working

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1725] opened 2023-10-02 13:55 UTC
Version
-------

6.2.72

Installation method
-------------------

My own rpm, derived from the "official" Redhat RPM

Expected behavior
-----------------

When a message is sent to a moderated list the list moderators receive an email of the form:

```
Subject: Message for list test-dpc22 from dpc22@cam.ac.uk to be approved

One new message for list test-dpc22 from [dpc22@cam.ac.uk](mailto:dpc22@cam.ac.uk) arrived.

1 messages are awaiting moderation.
To view the messages, please click on the following URL:
[...]
To reject it (it will be removed):
https://lists.cam.ac.uk/sympa/reject/test-dpc22/3d616cd73a0d1471d20d614513e7a2fb
```
The list moderator should be able to click on the link  at the bottom to reject the message.

Actual behavior
---------------

When I click on the link I see the following error:
```
Internal Server Error

Sympa encountered an internal error.

Please contact the listmaster.

Error: Parameter $tpl is not defined at /usr/share/sympa/lib/Sympa/Message/Template.pm line 64.
Traceback

DIED: Parameter $tpl is not defined at /usr/share/sympa/lib/Sympa/Message/Template.pm line 64.
 at /usr/share/sympa/lib/Sympa/Message/Template.pm line 64.
	Sympa::Message::Template::new('Sympa::Message::Template', 'template', undef, 'data', HASH(0x43da6e0), 'context', Sympa::List <test-dpc22@lists.cam.ac.uk>, 'rcpt', 'dpc22@cam.ac.uk', ...) called at /usr/share/sympa/lib/Sympa/Spindle.pm line 42
	Sympa::Spindle::new('Sympa::Spindle::ProcessTemplate', 'context', Sympa::List <test-dpc22@lists.cam.ac.uk>, 'template', undef, 'rcpt', 'dpc22@cam.ac.uk', 'data', HASH(0x43da6e0), ...) called at /usr/share/sympa/lib/Sympa.pm line 394
	Sympa::send_file(Sympa::List <test-dpc22@lists.cam.ac.uk>, undef, 'dpc22@cam.ac.uk', HASH(0x43da6e0)) called at /usr/libexec/sympa/wwsympa.fcgi line 7600
	main::do_reject() called at /usr/libexec/sympa/wwsympa.fcgi line 1562
```

We see a trickle of these "Parameter $tpl is not defined" errors in the Sympa logs each day.

The last significant event was an upgrade from 6.2.70 to 6.2.72 back in July. I infer that it was probably working before that point, and that increased activity at the start of term has caused someone to actually report the issue.

**Comment by ldidry** [comment] 2023-10-02 14:50
You can apply the patch from https://github.com/sympa-community/sympa/pull/1687 🙂

**Comment by ikedas** [comment] 2023-10-03 00:41
duplicate of #1687.

**Closed by ikedas** 2023-10-03 00:41 UTC
Labels: bug, duplicate
