### ISSUE TITLE
Need multiple message selection in moderation page for reject multiple messages with 1 clic 

### ISSUE THREAD

**Issue by saumont** [sympa-community/sympa#407] opened 2018-09-03 06:29 UTC
The moderation page is very very slow (3'50" in order to reject one message that I don't need to display before). I would like a faster page and to be able to select multiple messages from the list in order to distribute or reject them. This page modindex  is so slow  that  it other page in firefox are frozen, firefox sugest to block modindex. 
Need also a defaut choice for not sending any reject message (this is one more clic for each spam received).

Regards
Serge

**Comment by ikedas** [comment] 2018-09-03 06:55
Hi @saumont,

If you have not, could you please check recent version (6.2.x)?

Anyway please let us know what version you are using.

**Comment by guillaumedesgranges** [comment] 2018-09-23 15:11
Hello,
I confirm that the ability to select multiple message to moderate is a real need. With about ten "opened" lists to moderate, it takes a very, very long time to moderate the messages one by one. I think it was a possibility on sympa 5.x (?)
I'm using the 6.2.16
Many thanks for your work.
Guillaume

**Comment by ikedas** [comment] 2018-09-23 22:33
Hi @saumont and @guillaumedesgranges,

> Need multiple message selection in moderation page for reject multiple messages with 1 clic

Maybe a duplicate of issue #122 solved on version 6.2.28.

> The moderation page is very very slow (3'50" in order to reject one message that I don't need to display before). I would like a faster page and to be able to select multiple messages from the list in order to distribute or reject them. This page modindex is so slow that it other page in firefox are frozen, firefox sugest to block modindex.

Perhaps this was solved with issue #368 on version 6.2.36.

If you feel the problems have not been solved, please re-open corresponding issue and add comments.  This issue #407 is closed.

**Closed by ikedas** 2018-09-23 22:33 UTC
