### ISSUE TITLE
send.public_nobcc scenario error

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#856] opened 2020-02-03 13:36 UTC
Version
-------
v 6.2.52

Installation method
-------------------
via EPEL repo, on RHEL 7.7 (Maipo)

Actual behavior
---------------

I am seeing the following in the logs: 

Error in scenario Sympa::Scenario <send.public_nobcc;/etc/sympa/scenari/send.public_nobcc>, context Sympa::List <listname@domain.com>: (Missing parameter 'is_bcc' at (eval 1256) line 6.#012)

It seems the "equal([is_bcc],1)" evaluation in the scenario is not working. I believe this was working in v6.2.48, before the update to the latest version 6.2.52

**Comment by ikedas** [comment] 2020-02-03 14:11
Looks a duplicate of #841 .

**Comment by laerm** [comment] 2020-02-04 09:07
I've applied the patch in #841 and the error has not occurred since. Seems to have done the trick, thank you!

**Closed** 2020-02-04 09:16 UTC
Labels: bug, duplicate
